import struct
import sys

data = open(sys.argv[1], "rb").read()
assert data[:4] == b"FCBM", data[:4]
version = struct.unpack(">I", data[4:8])[0]
assert version == 3, version
assert b"\x50" in data, data
assert b"\x40" in data, data
assert b"\x41" in data, data
assert b"\x42" in data, data
assert b"\x43" in data, data
assert b"\x44" in data, data
assert b"\x45" in data, data
assert b"\x55" in data, data
assert b"\x54" in data, data
assert b"\x60" in data, data
assert b"\x61" in data, data
assert b"\x62" in data, data
assert b"\x63" in data, data
assert b"\x64" in data, data
assert b"\x51" in data, data
assert b"\x53" in data, data
assert b"\x03" in data, data
assert b"\x04" in data, data
assert b"\x31" in data, data
assert b"\x30" in data, data
assert b"enabled" in data, data
assert b"premium" in data, data
assert b"state" in data, data
assert b"tier" in data, data
assert b"ready" in data, data
assert b"keepGoing" in data, data
assert b"next" in data, data
assert b"segment" in data, data
assert b"j" in data, data
assert b"prefix" in data, data
assert b"syncLocalMutation" in data, data
assert b"patched-local" in data, data
assert b"asyncLocalMutation" in data, data
assert b"patched-async-local" in data, data
assert b"asyncAwaitThenLocalMutation" in data, data
assert b"patched-await-local:" in data, data
assert b"asyncUpdateConfigLabel" in data, data
assert b"async-patched" in data, data
assert b"asyncAwaitThenUpdateConfigLabel" in data, data
assert b"await-patched" in data, data
assert b"asyncDynamicNamedCall" in data, data
assert b"asyncAwaitThenDynamicCall" in data, data
assert b"patched-await-dynamic<" in data, data
assert b"patched-async" in data, data
assert b"asyncSameObject" in data, data
assert b"asyncAwaitThenSameObject" in data, data
assert b"asyncAwaitThenIsString" in data, data
assert b"asyncAwaitThenAsStringList" in data, data
assert b"dart:core::identical" in data, data
assert b"asyncDisplayName" in data, data
assert b"asyncAwaitThenReadField" in data, data
assert b"patched-await-field" in data, data
assert b"asyncMakeUser" in data, data
assert b"asyncAwaitThenMakeUser" in data, data
assert b"patched-await-user" in data, data
assert b"asyncMakeConfig" in data, data
assert b"asyncAwaitThenMakeConfig" in data, data
assert b"patched-await-config" in data, data
assert b"asyncMakeStringBox" in data, data
assert b"asyncAwaitThenMakeStringBox" in data, data
assert b"patched-await-box:" in data, data
assert b"package:fcb_kernel_compile_test/main.dart::class:Box.;types:String" in data, data
assert b"patched-async-label" in data, data
assert b"asyncIfElseBothTryFinallyAwaitTail" in data, data
assert b"patched-ifelse-both-try-finally-await-tail" in data, data
assert b"asyncIfElseBothTryCatchFinallyAwaitTail" in data, data
assert b"patched-ifelse-both-catch-finally-await-tail" in data, data
assert b"asyncWhileNestedAwaitBranchLocal" in data, data
assert b"patched-while-nested-await-branch" in data, data
assert b"asyncForNestedAwaitBranchLocal" in data, data
assert b"patched-for-nested-await-branch" in data, data
assert b"asyncForAwaitUpdateNestedBranchLocal" in data, data
assert b"patched-for-await-update-nested-branch" in data, data
assert b"asyncForTryFinallyAwaitGuard" in data, data
assert b"patched-for-try-finally-await-guard" in data, data
assert b"asyncForTryFinallyAwaitGuardAwaitUpdate" in data, data
assert b"patched-for-try-finally-await-guard-update" in data, data
assert b"asyncForTryCatchAwaitGuard" in data, data
assert b"patched-for-try-catch-await-guard" in data, data
assert b"asyncForTryCatchAwaitGuardAwaitUpdate" in data, data
assert b"patched-for-try-catch-await-guard-update" in data, data
assert b"asyncForAwaitConditionTryFinallyAwaitGuardAwaitUpdate" in data, data
assert b"patched-for-await-condition-try-finally-update" in data, data
assert b"asyncForAwaitConditionTryCatchAwaitGuardAwaitUpdate" in data, data
assert b"patched-for-await-condition-try-catch-update" in data, data
assert b"asyncWhileTryCatchAwaitGuard" in data, data
assert b"patched-while-try-catch-await-guard" in data, data
assert b"asyncWhileTryFinallyAwaitGuard" in data, data
assert b"patched-while-try-finally-await-guard" in data, data
assert b"asyncWhileAwaitConditionTryCatchAwaitGuard" in data, data
assert b"patched-while-await-condition-try-catch" in data, data
assert b"asyncWhileAwaitConditionTryFinallyAwaitGuard" in data, data
assert b"patched-while-await-condition-try-finally" in data, data
assert b"asyncDoWhileTryCatchAwaitGuard" in data, data
assert b"patched-do-while-try-catch-await-guard" in data, data
assert b"asyncDoWhileTryFinallyAwaitGuard" in data, data
assert b"patched-do-while-try-finally-await-guard" in data, data
assert b"asyncDoWhileAwaitConditionTryCatchAwaitGuard" in data, data
assert b"patched-do-while-await-condition-try-catch" in data, data
assert b"asyncDoWhileAwaitConditionTryFinallyAwaitGuard" in data, data
assert b"patched-do-while-await-condition-try-finally" in data, data
assert b"asyncForMultiUpdateBranchLocal" in data, data
assert b"patched-for-multi-update-pro" in data, data
assert b"asyncForAwaitConditionMultiUpdateBranchLocal" in data, data
assert b"patched-for-await-condition-multi-update-pro" in data, data
assert b"asyncForMultiAwaitUpdateNestedBranchLocal" in data, data
assert b"patched-for-multi-await-update-nested-pro" in data, data
assert b"asyncForMultiUpdateTryFinallyAwaitGuard" in data, data
assert b"patched-for-multi-update-try-finally" in data, data
assert b"asyncForAwaitConditionMultiUpdateTryCatchAwaitGuard" in data, data
assert b"patched-for-await-condition-multi-update-error-" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateTryFinallyBranchLocal" in data, data
assert b"patched-for-await-condition-multi-await-update-try-finally-pro" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateTryCatchBranchLocal" in data, data
assert b"patched-for-await-condition-multi-await-update-try-catch-error-" in data, data
assert b"asyncForMultiAwaitUpdateTryFinallyNestedBranchLocal" in data, data
assert b"patched-for-multi-await-update-try-finally-nested-pro" in data, data
assert b"asyncForMultiAwaitUpdateTryCatchNestedBranchLocal" in data, data
assert b"patched-for-multi-await-update-try-catch-nested-error-" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateSwitchExprBranchLocal" in data, data
assert b"patched-for-await-condition-multi-await-update-switch-expr-pro" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateSwitchTryFinally" in data, data
assert b"patched-for-await-condition-multi-await-update-switch-finally-pro" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateSwitchTryCatch" in data, data
assert b"patched-for-await-condition-multi-await-update-switch-catch-error-" in data, data
assert b"asyncForMultiAwaitUpdateSwitchStatementNestedBranchLocal" in data, data
assert b"patched-for-multi-await-update-switch-stmt-pro" in data, data
assert b"asyncForMultiAwaitUpdateSwitchStatementTryFinallyNested" in data, data
assert b"patched-for-multi-await-update-switch-stmt-finally-pro" in data, data
assert b"asyncForMultiAwaitUpdateSwitchStatementTryCatchNested" in data, data
assert b"patched-for-multi-await-update-switch-stmt-catch-error-" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateNestedBranchTryFinally" in data, data
assert b"patched-for-await-condition-multi-await-update-nested-finally-special-" in data, data
assert b"asyncForMultiAwaitUpdateTryCatchFinallyNestedBranchLocal" in data, data
assert b"patched-for-multi-await-update-try-catch-finally-error-" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateSwitchExprNestedTryFinally" in data, data
assert b"patched-for-await-condition-multi-await-update-switch-expr-nested-finally-pro" in data, data
assert b"asyncForMultiAwaitUpdateSwitchStatementTryCatchFinallyNestedBranchLocal" in data, data
assert b"patched-for-multi-await-update-switch-stmt-catch-finally-error-" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateContinueBreakTryFinally" in data, data
assert b"patched-for-await-condition-multi-await-update-continue-break" in data, data
assert b"asyncForMultiAwaitUpdateNestedSwitchExprTryCatchBranchLocal" in data, data
assert b"patched-for-multi-await-update-nested-switch-expr-catch-error-" in data, data
assert b"asyncWhileTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-finalizer-guard" in data, data
assert b"asyncWhileAwaitConditionTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-await-condition-finalizer-guard" in data, data
assert b"asyncWhileNestedTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-nested-finalizer-guard" in data, data
assert b"asyncWhileTryCatchFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-catch-finalizer-guard-error-" in data, data
assert b"asyncDoWhileTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-finalizer-guard" in data, data
assert b"asyncDoWhileAwaitConditionTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-await-condition-finalizer-guard" in data, data
assert b"asyncDoWhileNestedTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-nested-finalizer-guard" in data, data
assert b"asyncDoWhileTryCatchFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-catch-finalizer-guard-error-" in data, data
assert b"asyncWhileSwitchTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-switch-finalizer-gold" in data, data
assert b"asyncDoWhileSwitchTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-switch-finalizer-gold" in data, data
assert b"asyncWhileSwitchOrPatternTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-switch-or-finalizer-premium" in data, data
assert b"asyncDoWhileSwitchOrPatternTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-switch-or-finalizer-premium" in data, data
assert b"asyncWhileCollectionTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-collection-finalizer-cleanup-" in data, data
assert b"asyncDoWhileCollectionTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-collection-finalizer-cleanup-" in data, data
assert b"asyncWhileMapCollectionTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-map-finalizer-cleanup-" in data, data
assert b"asyncDoWhileMapCollectionTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-map-finalizer-cleanup-" in data, data
assert b"asyncWhileCollectionSwitchForTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-collection-switch-finalizer-premium" in data, data
assert b"asyncDoWhileCollectionSwitchForTryFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-collection-switch-finalizer-premium" in data, data
assert b"asyncWhileMapSwitchForTryCatchFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-while-map-switch-finalizer-cleanup-" in data, data
assert b"asyncDoWhileMapSwitchForTryCatchFinallyAwaitGuardContinueBreak" in data, data
assert b"patched-do-map-switch-finalizer-cleanup-" in data, data
assert b"asyncGeneratedYieldStarStreamCatch" in data, data
assert b"patched-stream-yield-star-stream-caught-" in data, data
assert b"asyncGeneratedGuardedSwitchYieldFor" in data, data
assert b"patched-stream-guarded-switch-yield-for-gold-" in data, data
assert b"asyncGeneratedGuardedSwitchListCleanup" in data, data
assert b"patched-stream-guarded-switch-list-gold-" in data, data
assert b"asyncGeneratedGuardedSwitchMapRecoveryCleanup" in data, data
assert b"patched-stream-guarded-switch-map-caught-" in data, data
assert b"asyncGeneratedGuardedSwitchAwaitScrutineeYieldStar" in data, data
assert b"patched-stream-guarded-switch-await-scrutinee-cleanup-" in data, data
assert b"asyncGeneratedNestedGuardedSwitchAwaitForCollection" in data, data
assert b"patched-stream-nested-guarded-switch-cleanup-" in data, data
assert b"asyncGeneratedGuardedSwitchStatementMapRecoveryCleanup" in data, data
assert b"patched-stream-guarded-switch-stmt-map-blocked" in data, data
assert b"patched-stream-guarded-switch-stmt-map-cleanup-" in data, data
assert b"asyncGeneratedSwitchStatementYieldStarRecoveryCleanup" in data, data
assert b"patched-stream-switch-stmt-yield-star-blocked" in data, data
assert b"patched-stream-switch-stmt-yield-star-cleanup-tail-" in data, data
assert b"asyncGeneratedNestedSwitchStatementYieldStarListCleanup" in data, data
assert b"patched-stream-nested-switch-stmt-yield-star-list-blocked" in data, data
assert b"patched-stream-nested-switch-stmt-yield-star-list-cleanup-tail-" in data, data
assert b"syncGeneratedSwitchStatementYieldStarRecoveryCleanup" in data, data
assert b"patched-iterable-switch-stmt-yield-star-blocked" in data, data
assert b"patched-iterable-switch-stmt-yield-star-cleanup-head" in data, data
assert b"syncGeneratedNestedSwitchStatementListCleanup" in data, data
assert b"patched-iterable-nested-switch-stmt-list-blocked" in data, data
assert b"patched-iterable-nested-switch-stmt-list-cleanup-tail-" in data, data
assert b"asyncSwitchStatementAwaitScrutineeCollectionRecoveryCleanup" in data, data
assert b"patched-async-switch-stmt-collection-blocked" in data, data
assert b"patched-async-switch-stmt-collection-cleanup-" in data, data
assert b"asyncSwitchStatementMapRecoveryCleanup" in data, data
assert b"patched-async-switch-stmt-map-blocked" in data, data
assert b"patched-async-switch-stmt-map-cleanup-" in data, data
assert b"asyncGeneratedYieldStarStreamCatchFinally" in data, data
assert b"patched-stream-yield-star-stream-catch-finally-cleanup" in data, data
assert b"asyncGeneratedYieldStarStreamCatchAwaitRecovery" in data, data
assert b"patched-stream-yield-star-stream-catch-await-caught-" in data, data
assert b"asyncGeneratedYieldStarStreamFinallyAwaitCleanup" in data, data
assert b"patched-stream-yield-star-stream-finally-await-cleanup-" in data, data
assert b"asyncGeneratedYieldStarStreamCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-stream-catch-finally-await-cleanup-" in data, data
assert b"asyncGeneratedYieldStarTwoStreamsCatchFinally" in data, data
assert b"patched-stream-yield-star-two-streams-catch-finally-cleanup" in data, data
assert b"asyncGeneratedYieldStarTwoStreamsCatchAwaitRecovery" in data, data
assert b"patched-stream-yield-star-two-streams-catch-await-caught-" in data, data
assert b"asyncGeneratedYieldStarTwoStreamsFinallyAwaitCleanup" in data, data
assert b"patched-stream-yield-star-two-streams-finally-await-cleanup-" in data, data
assert b"asyncGeneratedYieldStarTwoStreamsCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-two-streams-catch-finally-await-cleanup-" in data, data
assert b"asyncCollectionSwitchSpreadNames" in data, data
assert b"patched-collection-switch-list-premium" in data, data
assert b"patched-collection-switch-list-for-" in data, data
assert b"asyncCollectionSwitchSpreadLabels" in data, data
assert b"patched-collection-switch-map-premium" in data, data
assert b"patched-collection-switch-map-for-" in data, data
assert b"asyncCollectionGuardedSwitchSpreadNames" in data, data
assert b"patched-collection-guarded-switch-list-gold" in data, data
assert b"patched-collection-guarded-switch-list-for-" in data, data
assert b"asyncCollectionGuardedSwitchSpreadLabels" in data, data
assert b"patched-collection-guarded-switch-map-gold" in data, data
assert b"patched-collection-guarded-switch-map-for-" in data, data
assert b"asyncCollectionSwitchTryFinallyNames" in data, data
assert b"patched-collection-switch-try-finally-list-cleanup" in data, data
assert b"asyncCollectionSwitchTryCatchLabels" in data, data
assert b"patched-collection-switch-try-catch-map-caught-" in data, data
assert b"asyncCollectionSwitchTryCatchFinallyAwaitNames" in data, data
assert b"patched-collection-switch-try-catch-finally-await-list-cleanup-" in data, data
assert b"asyncCollectionSwitchTryCatchFinallyAwaitLabels" in data, data
assert b"patched-collection-switch-try-catch-finally-await-map-cleanup-" in data, data
assert b"asyncAwaitThenCollectionSwitchSpreadNames" in data, data
assert b"patched-await-then-collection-switch-list-premium" in data, data
assert b"patched-await-then-collection-switch-list-for-" in data, data
assert b"asyncAwaitThenCollectionSwitchSpreadLabels" in data, data
assert b"patched-await-then-collection-switch-map-premium" in data, data
assert b"patched-await-then-collection-switch-map-for-" in data, data
assert b"asyncAwaitThenCollectionGuardedSwitchSpreadNames" in data, data
assert b"patched-await-then-collection-guarded-switch-list-gold" in data, data
assert b"patched-await-then-collection-guarded-switch-list-for-" in data, data
assert b"asyncAwaitThenCollectionGuardedSwitchSpreadLabels" in data, data
assert b"patched-await-then-collection-guarded-switch-map-gold" in data, data
assert b"patched-await-then-collection-guarded-switch-map-for-" in data, data
assert b"asyncAwaitThenCollectionSwitchTryFinallyNames" in data, data
assert b"patched-await-then-collection-switch-try-finally-list-cleanup" in data, data
assert b"asyncAwaitThenCollectionSwitchTryCatchLabels" in data, data
assert b"patched-await-then-collection-switch-try-catch-map-caught-" in data, data
assert b"asyncDoubleAwaitCollectionSwitchSpreadNames" in data, data
assert b"patched-double-await-collection-switch-list-premium" in data, data
assert b"patched-double-await-collection-switch-list-for-" in data, data
assert b"asyncDoubleAwaitCollectionSwitchSpreadLabels" in data, data
assert b"patched-double-await-collection-switch-map-premium" in data, data
assert b"patched-double-await-collection-switch-map-for-" in data, data
assert b"asyncDoubleAwaitCollectionGuardedSwitchSpreadNames" in data, data
assert b"patched-double-await-collection-guarded-switch-list-gold" in data, data
assert b"patched-double-await-collection-guarded-switch-list-for-" in data, data
assert b"asyncDoubleAwaitCollectionGuardedSwitchSpreadLabels" in data, data
assert b"patched-double-await-collection-guarded-switch-map-gold" in data, data
assert b"patched-double-await-collection-guarded-switch-map-for-" in data, data
assert b"asyncDoubleAwaitCollectionSwitchTryFinallyNames" in data, data
assert b"patched-double-await-collection-switch-try-finally-list-cleanup" in data, data
assert b"asyncDoubleAwaitCollectionSwitchTryCatchLabels" in data, data
assert b"patched-double-await-collection-switch-try-catch-map-caught-" in data, data
assert b"asyncDoubleAwaitCollectionSwitchTryCatchFinallyAwaitNames" in data, data
assert b"patched-double-await-collection-switch-try-catch-finally-await-list-cleanup-" in data, data
assert b"asyncDoubleAwaitCollectionSwitchTryCatchFinallyAwaitLabels" in data, data
assert b"patched-double-await-collection-switch-try-catch-finally-await-map-cleanup-" in data, data
assert b"asyncGeneratedAwaitForStreamCatch" in data, data
assert b"patched-stream-await-for-stream-caught-" in data, data
assert b"asyncGeneratedAwaitForStreamCatchFinally" in data, data
assert b"patched-stream-await-for-stream-catch-finally-cleanup" in data, data
assert b"asyncGeneratedAwaitForStreamCatchAwaitRecovery" in data, data
assert b"patched-stream-await-for-stream-catch-await-caught-" in data, data
assert b"asyncGeneratedAwaitForStreamFinallyAwaitCleanup" in data, data
assert b"patched-stream-await-for-stream-finally-await-cleanup-" in data, data
assert b"asyncGeneratedAwaitForStreamCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-await-for-stream-catch-finally-await-cleanup-" in data, data
assert b"asyncGeneratedAwaitForTwoStreamsCatchFinally" in data, data
assert b"patched-stream-await-for-two-streams-catch-finally-cleanup" in data, data
assert b"asyncGeneratedYieldStarStreamSandwichCatchFinally" in data, data
assert b"patched-stream-yield-star-stream-sandwich-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarTwoStreamsSandwichCatchFinally" in data, data
assert b"patched-stream-yield-star-two-streams-sandwich-cleanup" in data, data
assert b"asyncGeneratedYieldStarTripleStreamsCatchFinally" in data, data
assert b"patched-stream-yield-star-triple-streams-cleanup" in data, data
assert b"asyncGeneratedYieldStarTripleStreamsCatchAwaitRecovery" in data, data
assert b"patched-stream-yield-star-triple-streams-catch-await-caught-" in data, data
assert b"asyncGeneratedYieldStarTripleStreamsFinallyAwaitCleanup" in data, data
assert b"patched-stream-yield-star-triple-streams-finally-await-cleanup-" in data, data
assert b"asyncGeneratedYieldStarTripleStreamsCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-triple-streams-catch-finally-await-cleanup-" in data, data
assert b"asyncGeneratedAwaitForNestedStreamCatchFinally" in data, data
assert b"patched-stream-await-for-nested-stream-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForNestedStreamBreakContinueCatchFinally" in data, data
assert b"patched-stream-await-for-nested-stream-break-continue-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForTripleNestedStreamCatchFinally" in data, data
assert b"patched-stream-await-for-triple-nested-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarDynamicCatchFinally" in data, data
assert b"patched-stream-yield-star-dynamic-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarFromFutureCatchFinally" in data, data
assert b"patched-stream-yield-star-future-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarPendingFutureCatchFinally" in data, data
assert b"patched-stream-yield-star-pending-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForFromIterableCatchFinally" in data, data
assert b"patched-stream-await-for-iterable-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForFutureCatchFinally" in data, data
assert b"patched-stream-await-for-future-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForPendingFutureCatchFinally" in data, data
assert b"patched-stream-await-for-pending-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarValueCatchFinally" in data, data
assert b"patched-stream-yield-star-value-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarEmptyCatchFinally" in data, data
assert b"patched-stream-yield-star-empty-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForValueCatchFinally" in data, data
assert b"patched-stream-await-for-value-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForEmptyCatchFinally" in data, data
assert b"patched-stream-await-for-empty-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForFutureBreakCatchFinally" in data, data
assert b"patched-stream-await-for-future-break-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForPendingContinueCatchFinally" in data, data
assert b"patched-stream-await-for-pending-continue-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarNestedCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-nested-catch-finally-inner-" in data, data
assert b"patched-stream-yield-star-nested-catch-finally-cleanup-" in data, data
assert b"asyncGeneratedYieldStarNestedFinallyAwaitCleanup" in data, data
assert b"patched-stream-yield-star-nested-finally-inner-cleanup-" in data, data
assert b"asyncGeneratedAwaitForNestedCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-await-for-nested-catch-finally-await-caught-" in data, data
assert b"asyncGeneratedAwaitForTripleNestedCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-await-for-triple-nested-catch-finally-await-cleanup-" in data, data
assert b"asyncGeneratedYieldStarTripleNestedCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-triple-nested-catch-finally-inner-" in data, data
assert b"asyncGeneratedYieldStarTripleNestedFinallyAwaitCleanup" in data, data
assert b"patched-stream-yield-star-triple-nested-finally-inner-cleanup-" in data, data
assert b"asyncGeneratedAwaitForNestedBreakContinueCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-await-for-nested-break-continue-catch-finally-await-caught-" in data, data
assert b"asyncGeneratedAwaitForTripleNestedFinallyAwaitCleanup" in data, data
assert b"patched-stream-await-for-triple-nested-finally-await-cleanup-" in data, data
assert b"asyncGeneratedAwaitForSequentialCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-await-for-sequential-catch-finally-cleanup-" in data, data
assert b"asyncGeneratedAwaitForSequentialBreakContinueFinallyAwaitCleanup" in data, data
assert b"patched-stream-await-for-sequential-break-continue-cleanup-" in data, data
assert b"asyncGeneratedAwaitForNestedInnerCatchOuterFinallyAwaitRecovery" in data, data
assert b"patched-stream-await-for-nested-inner-catch-outer-finally-cleanup-" in data, data
assert b"asyncGeneratedYieldStarThenAwaitForCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-then-await-for-catch-finally-cleanup-" in data, data
assert b"asyncGeneratedAwaitForThenYieldStarFinallyAwaitCleanup" in data, data
assert b"patched-stream-await-for-then-yield-star-finally-cleanup-" in data, data
assert b"asyncGeneratedYieldStarAwaitForNestedCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-await-for-nested-catch-finally-cleanup-" in data, data
assert b"asyncGeneratedAwaitForSequentialNestedCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-await-for-sequential-nested-catch-finally-cleanup-" in data, data
assert b"asyncGeneratedAwaitForNestedThenYieldStarCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-await-for-nested-then-yield-star-cleanup-" in data, data
assert b"asyncGeneratedYieldStarThenAwaitForThenYieldStarCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-await-for-yield-star-cleanup-" in data, data
assert b"asyncGeneratedYieldStarNestedAwaitForThenYieldStarCatchFinallyAwaitRecovery" in data, data
assert b"patched-stream-yield-star-nested-await-for-yield-star-cleanup-" in data, data
assert b"asyncGeneratedAwaitForFinallyAwaitForCleanup" in data, data
assert b"patched-stream-await-for-finally-await-for-cleanup-" in data, data
assert b"asyncGeneratedYieldStarFinallyYieldStarCleanup" in data, data
assert b"patched-stream-yield-star-finally-yield-star-cleanup-head" in data, data
assert b"asyncGeneratedAwaitForCatchFinallyAwaitForCleanup" in data, data
assert b"patched-stream-await-for-catch-finally-await-for-cleanup-" in data, data
assert b"asyncGeneratedYieldStarAwaitForFinallyYieldStarCleanup" in data, data
assert b"patched-stream-yield-star-await-for-finally-yield-star-middle-" in data, data
assert b"syncGeneratedCollectionSwitchList" in data, data
assert b"patched-iterable-collection-switch-premium" in data, data
assert b"asyncGeneratedCollectionSwitchList" in data, data
assert b"patched-stream-collection-switch-premium" in data, data
assert b"asyncGeneratedAwaitCollectionTryFinallyList" in data, data
assert b"patched-stream-await-collection-try-finally-cleanup-" in data, data
assert b"asyncGeneratedCollectionSwitchTryCatchMap" in data, data
assert b"patched-stream-collection-switch-map-caught-" in data, data
assert b"syncGeneratedGuardedCollectionSwitchMap" in data, data
assert b"patched-iterable-guarded-collection-switch-map-premium" in data, data
assert b"syncGeneratedNestedCollectionForSwitchList" in data, data
assert b"patched-iterable-nested-collection-switch-premium" in data, data
assert b"asyncGeneratedAwaitThenCollectionSwitchMap" in data, data
assert b"patched-stream-await-then-collection-switch-map-premium" in data, data
assert b"asyncGeneratedDoubleAwaitGuardedCollectionList" in data, data
assert b"patched-stream-double-await-guarded-collection-premium" in data, data
assert b"asyncGeneratedCollectionSwitchTryCatchFinallyList" in data, data
assert b"patched-stream-collection-switch-list-cleanup-" in data, data
assert b"asyncGeneratedCollectionSwitchMapTryCatchFinallyAwait" in data, data
assert b"patched-stream-collection-switch-map-finally-cleanup-" in data, data
assert b"syncGeneratedNestedGuardedCollectionForList" in data, data
assert b"patched-iterable-nested-guarded-collection-list-premium" in data, data
assert b"asyncGeneratedAwaitThenNestedCollectionForSwitchList" in data, data
assert b"patched-stream-await-then-nested-collection-list-premium" in data, data
assert b"asyncGeneratedCollectionDynamicSpreadTryCatchFinallyList" in data, data
assert b"patched-stream-collection-dynamic-spread-list-cleanup-" in data, data
assert b"asyncGeneratedCollectionDynamicSpreadTryCatchFinallyMap" in data, data
assert b"patched-stream-collection-dynamic-spread-map-cleanup-" in data, data
assert b"syncGeneratedDynamicSpreadSwitchList" in data, data
assert b"patched-iterable-dynamic-spread-switch-list-premium" in data, data
assert b"asyncGeneratedDynamicSpreadSwitchList" in data, data
assert b"patched-stream-dynamic-spread-switch-list-premium" in data, data
assert b"syncGeneratedDynamicSpreadSwitchMap" in data, data
assert b"patched-iterable-dynamic-spread-switch-map-premium" in data, data
assert b"asyncGeneratedDynamicSpreadSwitchMap" in data, data
assert b"patched-stream-dynamic-spread-switch-map-premium" in data, data
assert b"asyncGeneratedDynamicSpreadSwitchTryFinallyList" in data, data
assert b"patched-stream-dynamic-spread-switch-try-finally-list" in data, data
assert b"asyncGeneratedDynamicSpreadSwitchTryCatchFinallyMap" in data, data
assert (
    b"patched-stream-dynamic-spread-switch-try-catch-finally-map"
    in data
), data
assert b"syncGeneratedSwitchOrPatternExpr" in data, data
assert b"patched-iterable-switch-or-premium" in data, data
assert b"syncGeneratedSwitchOrPatternStatement" in data, data
assert b"patched-iterable-switch-stmt-or-premium" in data, data
assert b"asyncGeneratedSwitchOrPatternExpr" in data, data
assert b"patched-stream-switch-or-premium" in data, data
assert b"asyncGeneratedSwitchOrPatternStatement" in data, data
assert b"patched-stream-switch-stmt-or-premium" in data, data
assert b"syncGeneratedGuardedSwitchExpr" in data, data
assert b"patched-iterable-guarded-switch-gold" in data, data
assert b"syncGeneratedGuardedSwitchStatement" in data, data
assert b"patched-iterable-guarded-switch-stmt-gold" in data, data
assert b"asyncGeneratedGuardedSwitchExpr" in data, data
assert b"patched-stream-guarded-switch-gold" in data, data
assert b"asyncGeneratedGuardedSwitchStatement" in data, data
assert b"patched-stream-guarded-switch-stmt-gold" in data, data
assert b"syncGeneratedWhileSwitchOrPatternStatement" in data, data
assert b"patched-iterable-while-switch-or-premium-" in data, data
assert b"syncGeneratedForSwitchOrPatternStatement" in data, data
assert b"patched-iterable-for-switch-or-premium-" in data, data
assert b"asyncGeneratedWhileSwitchOrPatternStatement" in data, data
assert b"patched-stream-while-switch-or-premium-" in data, data
assert b"asyncGeneratedForSwitchOrPatternStatement" in data, data
assert b"patched-stream-for-switch-or-premium-" in data, data
assert b"asyncGeneratedAwaitForSwitchOrPatternStatement" in data, data
assert b"patched-stream-await-for-switch-or-premium-" in data, data
assert b"asyncGeneratedNestedAwaitForSwitchOrPatternStatement" in data, data
assert b"patched-stream-nested-await-for-switch-or-premium-" in data, data
assert b"asyncGeneratedAwaitForSwitchOrPatternCatchFinally" in data, data
assert b"patched-stream-await-for-switch-or-catch-premium-" in data, data
assert b"patched-stream-await-for-switch-or-cleanup" in data, data
assert b"asyncGeneratedAwaitForSwitchOrPatternBreakContinueFinally" in data, data
assert b"patched-stream-await-for-switch-or-break-continue-premium-" in data, data
assert b"patched-stream-await-for-switch-or-break-continue-cleanup" in data, data
assert b"asyncGeneratedNestedAwaitForSwitchOrPatternCatchFinally" in data, data
assert b"patched-stream-nested-await-for-switch-or-catch-premium-" in data, data
assert b"patched-stream-nested-await-for-switch-or-cleanup" in data, data
assert b"asyncGeneratedNestedAwaitForSwitchOrPatternBreakContinueFinally" in data, data
assert b"patched-stream-nested-await-for-switch-or-break-continue-premium-" in data, data
assert b"patched-stream-nested-await-for-switch-or-break-continue-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchDynamicRuntimeNames" in data, data
assert b"patched-await-condition-try-catch-list-caught-" in data, data
assert b"asyncAwaitThenTryFinallyDynamicRuntimeNames" in data, data
assert b"patched-await-then-try-finally-list-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyRuntimeDynamicNames" in data, data
assert b"patched-await-condition-try-catch-finally-list-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-try-catch-map-caught-" in data, data
assert b"asyncAwaitThenTryFinallyDynamicRuntimeLabels" in data, data
assert b"patched-await-then-try-finally-map-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-try-catch-finally-map-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchDynamicRuntimeStaticSpreadNames" in data, data
assert b"patched-await-condition-try-catch-list-static-tail-a" in data, data
assert b"asyncAwaitThenTryFinallyRuntimeDynamicStaticSpreadNames" in data, data
assert b"patched-await-then-try-finally-list-static-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyDynamicRuntimeTailNames" in data, data
assert b"patched-await-condition-try-catch-finally-list-tail-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchDynamicRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-condition-try-catch-map-static-tail-a" in data, data
assert b"asyncAwaitThenTryFinallyRuntimeDynamicStaticSpreadLabels" in data, data
assert b"patched-await-then-try-finally-map-static-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyDynamicRuntimeTailLabels" in data, data
assert b"patched-await-condition-try-catch-finally-map-tail-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchRuntimeDynamicRuntimeNames" in data, data
assert b"patched-await-condition-try-catch-list-rdr-caught-" in data, data
assert b"asyncAwaitThenTryFinallyDynamicRuntimeDynamicNames" in data, data
assert b"patched-await-then-try-finally-list-drd-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyRuntimeRuntimeDynamicNames" in data, data
assert b"patched-await-condition-try-catch-finally-list-rrd-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchRuntimeDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-try-catch-map-rdr-caught-" in data, data
assert b"asyncAwaitThenTryFinallyDynamicRuntimeDynamicLabels" in data, data
assert b"patched-await-then-try-finally-map-drd-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyRuntimeRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-try-catch-finally-map-rrd-cleanup" in data, data
assert b"asyncCollectionTryCatchAwaitRecoveryNames" in data, data
assert b"patched-collection-try-catch-await-list-caught-" in data, data
assert b"asyncCollectionTryFinallyAwaitCleanupNames" in data, data
assert b"patched-collection-try-finally-await-list-cleanup-" in data, data
assert b"asyncCollectionTryCatchFinallyAwaitRecoveryNames" in data, data
assert b"patched-collection-try-catch-finally-await-list-cleanup-" in data, data
assert b"asyncCollectionTryCatchAwaitRecoveryLabels" in data, data
assert b"patched-collection-try-catch-await-map-caught-" in data, data
assert b"asyncCollectionTryFinallyAwaitCleanupLabels" in data, data
assert b"patched-collection-try-finally-await-map-cleanup-" in data, data
assert b"asyncCollectionTryCatchFinallyAwaitRecoveryLabels" in data, data
assert b"patched-collection-try-catch-finally-await-map-cleanup-" in data, data
assert b"asyncAwaitThenCollectionTryCatchAwaitRecoveryNames" in data, data
assert b"patched-await-then-collection-try-catch-await-list-caught-" in data, data
assert b"asyncAwaitThenCollectionTryFinallyAwaitCleanupNames" in data, data
assert b"patched-await-then-collection-try-finally-await-list-cleanup-" in data, data
assert b"asyncAwaitThenCollectionTryCatchFinallyAwaitRecoveryNames" in data, data
assert b"patched-await-then-collection-try-catch-finally-await-list-cleanup-" in data, data
assert b"asyncAwaitThenCollectionTryCatchAwaitRecoveryLabels" in data, data
assert b"patched-await-then-collection-try-catch-await-map-caught-" in data, data
assert b"asyncAwaitThenCollectionTryFinallyAwaitCleanupLabels" in data, data
assert b"patched-await-then-collection-try-finally-await-map-cleanup-" in data, data
assert b"asyncAwaitThenCollectionTryCatchFinallyAwaitRecoveryLabels" in data, data
assert b"patched-await-then-collection-try-catch-finally-await-map-cleanup-" in data, data
assert b"asyncDoubleAwaitCollectionTryCatchAwaitRecoveryNames" in data, data
assert b"patched-double-await-collection-try-catch-await-list-caught-" in data, data
assert b"asyncDoubleAwaitCollectionTryFinallyAwaitCleanupNames" in data, data
assert b"patched-double-await-collection-try-finally-await-list-cleanup-" in data, data
assert b"asyncDoubleAwaitCollectionTryCatchFinallyAwaitRecoveryNames" in data, data
assert b"patched-double-await-collection-try-catch-finally-await-list-cleanup-" in data, data
assert b"asyncDoubleAwaitCollectionTryCatchAwaitRecoveryLabels" in data, data
assert b"patched-double-await-collection-try-catch-await-map-caught-" in data, data
assert b"asyncDoubleAwaitCollectionTryFinallyAwaitCleanupLabels" in data, data
assert b"patched-double-await-collection-try-finally-await-map-cleanup-" in data, data
assert b"asyncDoubleAwaitCollectionTryCatchFinallyAwaitRecoveryLabels" in data, data
assert b"patched-double-await-collection-try-catch-finally-await-map-cleanup-" in data, data
assert b"syncSwitchLabel" in data, data
assert b"patched-switch-gold" in data, data
assert b"syncSwitchMultiValueLabel" in data, data
assert b"patched-switch-premium" in data, data
assert b"asyncSwitchLabel" in data, data
assert b"patched-async-switch-gold" in data, data
assert b"asyncSwitchMultiValueLabel" in data, data
assert b"patched-async-switch-premium" in data, data
assert b"asyncAwaitThenSwitchLabel" in data, data
assert b"patched-await-switch-gold" in data, data
assert b"asyncAwaitThenSwitchMultiValueLabel" in data, data
assert b"patched-await-switch-premium" in data, data
assert b"unchangedGuardedSwitchLabel" in data, data
assert b"patched-guarded-switch-gold" in data, data
assert b"patched-guarded-switch-vip" in data, data
assert b"asyncGuardedSwitchLabel" in data, data
assert b"patched-async-guarded-switch-gold" in data, data
assert b"patched-async-guarded-switch-vip" in data, data
assert b"asyncAwaitThenGuardedSwitchLabel" in data, data
assert b"patched-await-guarded-switch-gold" in data, data
assert b"patched-await-guarded-switch-vip" in data, data
assert b"syncSwitchScore" in data, data
assert b"syncSwitchMultiValueScore" in data, data
assert b"switchListNames" in data, data
assert b"patched-switch-list-gold" in data, data
assert b"switchMapLabels" in data, data
assert b"patched-switch-map-seven" in data, data
assert b"asyncAwaitConditionSwitchTryCatchRecoveryLabel" in data, data
assert b"patched-await-condition-switch-try-catch-caught-" in data, data
assert b"asyncAwaitConditionSwitchTryFinallyCleanupLabel" in data, data
assert b"patched-await-condition-switch-try-finally-gold" in data, data
assert b"asyncAwaitThenSwitchTryCatchRecoveryLabel" in data, data
assert b"patched-await-then-switch-try-catch-caught-" in data, data
assert b"asyncAwaitThenSwitchTryFinallyCleanupLabel" in data, data
assert b"patched-await-then-switch-try-finally-gold" in data, data
assert b"asyncDoubleAwaitSwitchTryCatchFinallyRecoveryLabel" in data, data
assert b"patched-double-await-switch-try-catch-finally-caught-" in data, data
assert b"asyncDoubleAwaitSwitchTryFinallyCleanupLabel" in data, data
assert b"patched-double-await-switch-try-finally-gold" in data, data
assert b"asyncSwitchAwaitGuardLabel" in data, data
assert b"patched-switch-await-guard-gold" in data, data
assert b"asyncAwaitThenSwitchAwaitGuardLabel" in data, data
assert b"patched-await-switch-await-guard-gold" in data, data
assert b"syncSwitchStatementLabel" in data, data
assert b"patched-switch-stmt-gold" in data, data
assert b"asyncSwitchStatementLabel" in data, data
assert b"patched-async-switch-stmt-gold" in data, data
assert b"asyncAwaitThenSwitchStatementLabel" in data, data
assert b"patched-await-switch-stmt-gold" in data, data
assert b"unchangedGuardedSwitchStatementLabel" in data, data
assert b"patched-guarded-switch-stmt-gold" in data, data
assert b"patched-guarded-switch-stmt-vip" in data, data
assert b"asyncGuardedSwitchStatementLabel" in data, data
assert b"patched-async-guarded-switch-stmt-gold" in data, data
assert b"patched-async-guarded-switch-stmt-vip" in data, data
assert b"asyncAwaitThenGuardedSwitchStatementLabel" in data, data
assert b"patched-await-guarded-switch-stmt-gold" in data, data
assert b"patched-await-guarded-switch-stmt-vip" in data, data
assert b"syncSwitchStatementScore" in data, data
assert b"switchStatementListNames" in data, data
assert b"patched-switch-stmt-list-gold" in data, data
assert b"switchStatementMapLabels" in data, data
assert b"patched-switch-stmt-map-seven" in data, data
assert b"syncSwitchStatementAssignedLabel" in data, data
assert b"patched-switch-stmt-assigned-gold" in data, data
assert b"asyncSwitchStatementAssignedLabel" in data, data
assert b"patched-async-switch-stmt-assigned-gold" in data, data
assert b"asyncAwaitThenSwitchStatementAssignedLabel" in data, data
assert b"patched-await-switch-stmt-assigned-gold" in data, data
assert b"syncSwitchStatementAssignedScore" in data, data
assert b"syncSwitchStatementThrowLabel" in data, data
assert b"patched-switch-stmt-throw-blocked" in data, data
assert b"asyncSwitchStatementThrowLabel" in data, data
assert b"patched-async-switch-stmt-throw-blocked" in data, data
assert b"asyncAwaitThenSwitchStatementThrowLabel" in data, data
assert b"patched-await-switch-stmt-throw-blocked" in data, data
assert b"syncSwitchStatementSequenceLabel" in data, data
assert b"patched-switch-stmt-seq-blocked" in data, data
assert b"asyncSwitchStatementSequenceLabel" in data, data
assert b"patched-async-switch-stmt-seq-blocked" in data, data
assert b"asyncAwaitThenSwitchStatementSequenceLabel" in data, data
assert b"patched-await-switch-stmt-seq-blocked" in data, data
assert b"syncSwitchStatementSideEffectTail" in data, data
assert b"patched-switch-stmt-side-suffix-gold" in data, data
assert b"asyncSwitchStatementSideEffectTail" in data, data
assert b"patched-async-switch-stmt-side-suffix-gold" in data, data
assert b"asyncAwaitThenSwitchStatementSideEffectTail" in data, data
assert b"patched-await-switch-stmt-side-suffix-gold" in data, data
assert b"asyncSwitchStatementAwaitCaseLabel" in data, data
assert b"patched-async-switch-stmt-await-case-blocked-" in data, data
assert b"asyncAwaitThenSwitchStatementAwaitCaseLabel" in data, data
assert b"patched-await-switch-stmt-await-case-blocked-" in data, data
assert b"syncSwitchStatementMultiCaseLabel" in data, data
assert b"patched-switch-stmt-multi-premium" in data, data
assert b"asyncSwitchStatementMultiCaseAssignedLabel" in data, data
assert b"patched-async-switch-stmt-multi-premium" in data, data
assert b"asyncSwitchStatementMultiCaseAwaitCaseLabel" in data, data
assert b"patched-async-switch-stmt-multi-await-blocked-" in data, data
assert b"syncSwitchStatementOrPatternLabel" in data, data
assert b"patched-switch-stmt-or-premium" in data, data
assert b"asyncSwitchStatementOrPatternAssignedLabel" in data, data
assert b"patched-async-switch-stmt-or-premium" in data, data
assert b"asyncSwitchStatementOrPatternAwaitCaseLabel" in data, data
assert b"patched-async-switch-stmt-or-await-blocked-" in data, data
assert b"asyncAwaitThenSwitchStatementOrPatternLabel" in data, data
assert b"patched-await-switch-stmt-or-premium" in data, data
assert b"asyncAwaitConditionSwitchStatementTryCatchRecoveryLabel" in data, data
assert b"patched-await-condition-switch-stmt-try-catch-caught-" in data, data
assert b"asyncAwaitConditionSwitchStatementTryFinallyCleanupLabel" in data, data
assert b"patched-await-condition-switch-stmt-try-finally-gold" in data, data
assert b"asyncAwaitThenSwitchStatementTryCatchRecoveryLabel" in data, data
assert b"patched-await-then-switch-stmt-try-catch-caught-" in data, data
assert b"asyncAwaitThenSwitchStatementTryFinallyCleanupLabel" in data, data
assert b"patched-await-then-switch-stmt-try-finally-gold" in data, data
assert b"asyncDoubleAwaitSwitchStatementTryCatchFinallyRecoveryLabel" in data, data
assert b"patched-double-await-switch-stmt-try-catch-finally-caught-" in data, data
assert b"asyncDoubleAwaitSwitchStatementTryFinallyCleanupLabel" in data, data
assert b"patched-double-await-switch-stmt-try-finally-gold" in data, data
assert b"asyncSwitchStatementAwaitGuardLabel" in data, data
assert b"patched-switch-stmt-await-guard-gold" in data, data
assert b"asyncAwaitThenSwitchStatementAwaitGuardLabel" in data, data
assert b"patched-await-switch-stmt-await-guard-gold" in data, data
assert b"switchStatementAssignedListNames" in data, data
assert b"patched-switch-stmt-assigned-list-gold" in data, data
assert b"switchStatementAssignedMapLabels" in data, data
assert b"patched-switch-stmt-assigned-map-seven" in data, data
assert b"asyncWhileSwitchAssignedLabel" in data, data
assert b"patched-while-switch-gold" in data, data
assert b"asyncWhileAwaitConditionSwitchAssignedLabel" in data, data
assert b"patched-while-await-switch-gold" in data, data
assert b"asyncForSwitchAssignedLabel" in data, data
assert b"patched-for-switch-gold" in data, data
assert b"asyncForAwaitUpdateSwitchAssignedLabel" in data, data
assert b"patched-for-await-update-switch-gold" in data, data
assert b"asyncForSwitchAssignedListNames" in data, data
assert b"patched-for-switch-list-gold" in data, data
assert b"asyncForSwitchAssignedMapLabels" in data, data
assert b"patched-for-switch-map-seven" in data, data
assert b"asyncDoWhileSwitchAssignedLabel" in data, data
assert b"patched-do-while-switch-gold" in data, data
assert b"asyncWhileSwitchOrPatternAssignedLabel" in data, data
assert b"patched-while-switch-or-premium" in data, data
assert b"asyncForAwaitUpdateSwitchOrPatternAssignedLabel" in data, data
assert b"patched-for-await-update-switch-or-premium" in data, data
assert b"asyncWhileNestedBranchSwitchAssignedLabel" in data, data
assert b"patched-while-nested-switch-gold" in data, data
assert b"asyncForTryCatchSwitchAssignedLabel" in data, data
assert b"patched-for-try-catch-switch-gold" in data, data
assert b"asyncForAwaitUpdateTryFinallySwitchAssignedLabel" in data, data
assert b"patched-for-await-update-try-finally-switch-gold" in data, data
assert b"asyncWhileAwaitConditionTryCatchSwitchAssignedLabel" in data, data
assert b"patched-while-await-condition-try-catch-switch-gold" in data, data
assert b"asyncWhileAwaitConditionTryCatchSwitchOrPatternAssignedLabel" in data, data
assert b"patched-while-await-condition-try-catch-switch-or-premium" in data, data
assert b"asyncDoWhileTryFinallySwitchAssignedLabel" in data, data
assert b"patched-do-while-try-finally-switch-gold" in data, data
assert b"asyncDoWhileTryFinallySwitchOrPatternAssignedLabel" in data, data
assert b"patched-do-while-try-finally-switch-or-premium" in data, data
assert b"awaitedCatchTail" in data, data
assert b"patched-catch-tail" in data, data
assert b"awaitedCatchAwaitTail" in data, data
assert b"patched-catch-await-tail" in data, data
assert b"awaitedCatchFinallyCleanup" in data, data
assert b"patched-catch-finally-ok-" in data, data
assert b"patched-catch-finally-caught-" in data, data
assert b"awaitedCatchFinallyAwaitTail" in data, data
assert b"patched-catch-finally-await-tail" in data, data
assert b"awaitedFinallyStatementTail" in data, data
assert b"patched-finally-tail" in data, data
assert b"patched-finally-tail-cleanup" in data, data
assert b"awaitedFinallyAwaitCleanupTail" in data, data
assert b"patched-finally-await-tail" in data, data
assert b"-cleanup-" in data, data
assert b"syncTryFinallyTail" in data, data
assert b"patched-sync-finally" in data, data
assert b"syncTryCatchTail" in data, data
assert b"patched-sync-catch" in data, data
assert b"syncTryCatchLocalStatementTail" in data, data
assert b"patched-sync-catch-local-statement" in data, data
assert b"patched-sync-catch-local-message-" in data, data
assert b"syncTryCatchBodyLocalStatementTail" in data, data
assert b"patched-sync-catch-body-local-statement" in data, data
assert b"patched-sync-catch-body-local-message-" in data, data
assert b"patched-sync-catch-body-local-caught-" in data, data
assert b"syncTryCatchReturnValue" in data, data
assert b"patched-catch-return-" in data, data
assert b"patched-caught-return-" in data, data
assert b"syncTryCatchLocalReturnValue" in data, data
assert b"patched-catch-local-return-" in data, data
assert b"patched-catch-local-caught-" in data, data
assert b"syncTryCatchFinallyReturnValue" in data, data
assert b"patched-catch-finally-return-" in data, data
assert b"patched-catch-finally-caught-" in data, data
assert b"patched-catch-finally-cleanup-" in data, data
assert b"syncTryCatchStatementTail" in data, data
assert b"patched-sync-catch-statement-" in data, data
assert b"syncTryFinallyStatementTail" in data, data
assert b"patched-sync-finally-statement-" in data, data
assert b"syncTryFinallyLocalStatementTail" in data, data
assert b"patched-cleanup-local-" in data, data
assert b"patched-sync-finally-local-statement-" in data, data
assert b"syncTryFinallyBodyLocalStatementTail" in data, data
assert b"patched-finally-body-local-" in data, data
assert b"patched-finally-body-cleanup-" in data, data
assert b"patched-sync-finally-body-local-statement-" in data, data
assert b"syncTryFinallyStatementVoid" in data, data
assert b"patched-void-cleanup-" in data, data
assert b"syncTryCatchStatementVoid" in data, data
assert b"patched-catch-void-" in data, data
assert b"syncTryFinallyReturnValue" in data, data
assert b"patched-finally-return-" in data, data
assert b"patched-return-cleanup-" in data, data
assert b"syncIfSideEffectTail" in data, data
assert b"patched-if-side-effect-" in data, data
assert b"patched-if-tail-" in data, data
assert b"syncIfElseSideEffectTail" in data, data
assert b"patched-ifelse-side-effect-on-" in data, data
assert b"patched-ifelse-side-effect-off-" in data, data
assert b"patched-ifelse-tail-" in data, data
assert b"syncIfElseLocalSideEffectTail" in data, data
assert b"patched-ifelse-local-on-" in data, data
assert b"patched-ifelse-local-off-" in data, data
assert b"patched-ifelse-local-tail-" in data, data
assert b"asyncIfElseSideEffectTail" in data, data
assert b"patched-ifelse-side-effect" in data, data
assert b"asyncIfSideEffectTail" in data, data
assert b"patched-if-side-effect" in data, data
assert b"asyncIfTryFinallyAwaitTail" in data, data
assert b"patched-if-try-finally-await-tail" in data, data
assert b"asyncIfTryCatchAwaitTail" in data, data
assert b"patched-if-try-catch-await-tail" in data, data
assert b"asyncIfElseTryFinallyCatchAwaitTail" in data, data
assert b"patched-ifelse-try-finally-catch-await-tail" in data, data
assert b"asyncConditionalAwaitExpr" in data, data
assert b"patched-conditional-disabled" in data, data
assert b"asyncConditionalBothAwaitExpr" in data, data
assert b"asyncAwaitConditionConditionalBothAwaitExpr" in data, data
assert b"asyncNestedConditionalAwaitExpr" in data, data
assert b"asyncAwaitConditionNestedConditionalAwaitExpr" in data, data
assert b"asyncLogicalAndAwaitLeft" in data, data
assert b"asyncLogicalAndAwaitRight" in data, data
assert b"asyncLogicalOrAwaitLeft" in data, data
assert b"asyncNestedLogicalAwait" in data, data
assert b"asyncIfLogicalAndAwaitTail" in data, data
assert b"asyncIfElseLogicalOrAwaitTail" in data, data
assert b"asyncIfNestedLogicalAwaitReturn" in data, data
assert b"asyncWhileLogicalAwaitCondition" in data, data
assert b"asyncDoWhileLogicalAwaitCondition" in data, data
assert b"asyncForLogicalAwaitCondition" in data, data
assert b"asyncIfTryFinallyLogicalAwaitTail" in data, data
assert b"asyncIfTryCatchLogicalAwaitTail" in data, data
assert b"asyncLogicalCollectionSpreadNames" in data, data
assert b"asyncLogicalCollectionSpreadLabels" in data, data
assert b"asyncLogicalCollectionForNames" in data, data
assert b"asyncLogicalCollectionForLabels" in data, data
assert b"asyncLogicalCollectionTryFinallyNames" in data, data
assert b"asyncLogicalCollectionTryFinallyLabels" in data, data
assert b"asyncLogicalCollectionTryCatchNames" in data, data
assert b"asyncLogicalCollectionTryCatchLabels" in data, data
assert b"asyncLogicalCollectionTryCatchFinallyNames" in data, data
assert b"asyncLogicalCollectionTryCatchFinallyLabels" in data, data
assert (
    b"asyncWhileAwaitConditionCollectionSwitchTryFinallyAwaitGuardContinueBreak"
    in data
), data
assert (
    b"asyncDoWhileAwaitConditionMapSwitchForTryCatchFinallyAwaitGuardContinueBreak"
    in data
), data
assert b"asyncWhileNestedCollectionTryFinallyAwaitGuard" in data, data
assert b"patched-while-nested-collection-finalizer" in data, data
assert b"asyncDoWhileNestedMapTryCatchFinallyAwaitGuard" in data, data
assert b"patched-do-nested-map-finalizer" in data, data
assert b"asyncForAwaitConditionMultiAwaitUpdateCollectionTryFinallyList" in data, data
assert (
    b"patched-for-await-condition-multi-await-update-collection-list"
    in data
), data
assert b"asyncForMultiAwaitUpdateCollectionTryCatchFinallyMap" in data, data
assert b"patched-for-multi-await-update-collection-map" in data, data
assert b"asyncGeneratedAwaitForYieldStarFinallyAwaitForCleanup" in data, data
assert b"asyncGeneratedYieldStarFinallyAwaitForYieldStarCleanup" in data, data
assert b"asyncAwaitThenChooseLabel" in data, data
assert b"patched-await-live" in data, data
assert b"asyncLessThanAwaitTail" in data, data
assert b"patched-less-than-tail" in data, data
assert b"asyncLessEqualAwaitTail" in data, data
assert b"patched-less-equal-tail" in data, data
assert b"asyncGreaterEqualAwaitTail" in data, data
assert b"patched-greater-equal-tail" in data, data
assert b"asyncNotEqualAwaitTail" in data, data
assert b"patched-not-equal-tail" in data, data
assert b"asyncIsStringList" in data, data
assert b"asyncAsStringList" in data, data
assert b"asyncDynamicNames" in data, data
assert b"asyncRuntimeForNames" in data, data
assert b"asyncRuntimeForLabels" in data, data
assert b"patched-async-for" in data, data
assert b"asyncAwaitThenRuntimeForNames" in data, data
assert b"asyncDynamicLabels" in data, data
assert b"asyncNames" in data, data
assert b"asyncAwaitThenNames" in data, data
assert b"patched-await-list" in data, data
assert b"asyncAwaitThenConditionalNames" in data, data
assert b"patched-await-if-live" in data, data
assert b"asyncAwaitThenConditionalDynamicNames" in data, data
assert b"patched-await-if-dynamic-live" in data, data
assert b"asyncAwaitThenConditionalDynamicTailNames" in data, data
assert b"patched-await-if-dynamic-tail-tail" in data, data
assert b"asyncAwaitThenConditionalDynamicStaticSpreadNames" in data, data
assert b"patched-await-if-dynamic-static-spread-tail-b" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeNames" in data, data
assert b"patched-await-if-dynamic-runtime-live" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeTailNames" in data, data
assert b"patched-await-if-dynamic-runtime-tail-tail" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeStaticSpreadNames" in data, data
assert b"patched-await-if-dynamic-runtime-static-spread-tail-b" in data, data
assert b"asyncAwaitThenConditionalRuntimeNames" in data, data
assert b"patched-await-if-runtime-live" in data, data
assert b"asyncAwaitThenConditionalRuntimeTailNames" in data, data
assert b"patched-await-if-runtime-tail-tail" in data, data
assert b"asyncAwaitThenConditionalRuntimeStaticSpreadNames" in data, data
assert b"patched-await-if-runtime-static-spread-tail-b" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicNames" in data, data
assert b"patched-await-if-runtime-dynamic-live" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicTailNames" in data, data
assert b"patched-await-if-runtime-dynamic-tail-tail" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicStaticSpreadNames" in data, data
assert b"patched-await-if-runtime-dynamic-static-spread-tail-b" in data, data
assert b"asyncAwaitConditionNames" in data, data
assert b"patched-await-condition-live" in data, data
assert b"asyncAwaitConditionDynamicNames" in data, data
assert b"patched-await-condition-dynamic-live" in data, data
assert b"asyncAwaitConditionRuntimeNames" in data, data
assert b"patched-await-condition-runtime-live" in data, data
assert b"asyncAwaitConditionDynamicRuntimeNames" in data, data
assert b"patched-await-condition-chain-live" in data, data
assert b"asyncAwaitConditionDynamicRuntimeStaticSpreadNames" in data, data
assert b"patched-await-condition-chain-static-spread-tail-b" in data, data
assert b"asyncAwaitConditionDynamicRuntimeTailNames" in data, data
assert b"patched-await-condition-chain-tail-tail" in data, data
assert b"asyncAwaitConditionDynamicRuntimeDynamicNames" in data, data
assert b"patched-await-condition-chain-dynamic-live" in data, data
assert b"asyncAwaitConditionDynamicDynamicRuntimeNames" in data, data
assert b"patched-await-condition-double-dynamic-runtime-live" in data, data
assert b"asyncAwaitConditionDynamicDynamicDynamicNames" in data, data
assert b"patched-await-condition-triple-dynamic-live" in data, data
assert b"asyncAwaitConditionRuntimeDynamicNames" in data, data
assert b"patched-await-condition-reverse-chain-live" in data, data
assert b"asyncAwaitConditionRuntimeDynamicStaticSpreadNames" in data, data
assert b"patched-await-condition-reverse-chain-static-spread-tail-b" in data, data
assert b"asyncAwaitConditionRuntimeDynamicTailNames" in data, data
assert b"patched-await-condition-reverse-chain-tail-tail" in data, data
assert b"asyncAwaitConditionRuntimeDynamicRuntimeNames" in data, data
assert b"patched-await-condition-reverse-chain-runtime-live" in data, data
assert b"asyncAwaitConditionRuntimeRuntimeDynamicNames" in data, data
assert b"patched-await-condition-double-runtime-dynamic-live" in data, data
assert b"asyncAwaitConditionRuntimeRuntimeRuntimeNames" in data, data
assert b"patched-await-condition-triple-runtime-live" in data, data
assert b"asyncAwaitConditionDynamicTailNames" in data, data
assert b"patched-await-condition-tail-chain-tail" in data, data
assert b"asyncAwaitConditionRuntimeTailNames" in data, data
assert b"patched-await-condition-runtime-tail-tail" in data, data
assert b"asyncAwaitConditionDynamicStaticSpreadNames" in data, data
assert b"patched-await-condition-static-spread-tail-b" in data, data
assert b"asyncAwaitConditionRuntimeStaticSpreadNames" in data, data
assert b"patched-await-condition-runtime-static-spread-tail-b" in data, data
assert b"asyncAwaitThenDynamicNames" in data, data
assert b"patched-await-dynamic" in data, data
assert b"asyncLabels" in data, data
assert b"asyncAwaitThenLabels" in data, data
assert b"patched-await-map" in data, data
assert b"asyncAwaitThenConditionalLabels" in data, data
assert b"patched-await-if-map" in data, data
assert b"asyncAwaitThenConditionalDynamicLabels" in data, data
assert b"patched-await-if-dynamic-map" in data, data
assert b"asyncAwaitThenConditionalDynamicTailLabels" in data, data
assert b"patched-await-if-dynamic-tail-map" in data, data
assert b"asyncAwaitThenConditionalDynamicStaticSpreadLabels" in data, data
assert b"patched-await-if-dynamic-static-spread-map" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeLabels" in data, data
assert b"patched-await-if-dynamic-runtime-map" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeTailLabels" in data, data
assert b"patched-await-if-dynamic-runtime-tail-map" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-if-dynamic-runtime-static-spread-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeLabels" in data, data
assert b"patched-await-if-runtime-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeTailLabels" in data, data
assert b"patched-await-if-runtime-tail-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-if-runtime-static-spread-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicLabels" in data, data
assert b"patched-await-if-runtime-dynamic-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicTailLabels" in data, data
assert b"patched-await-if-runtime-dynamic-tail-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicStaticSpreadLabels" in data, data
assert b"patched-await-if-runtime-dynamic-static-spread-map" in data, data
assert b"asyncAwaitConditionLabels" in data, data
assert b"patched-await-condition-map" in data, data
assert b"asyncAwaitConditionDynamicLabels" in data, data
assert b"patched-await-condition-dynamic-map" in data, data
assert b"asyncAwaitConditionRuntimeLabels" in data, data
assert b"patched-await-condition-runtime-map" in data, data
assert b"asyncAwaitConditionDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-chain-map" in data, data
assert b"asyncAwaitConditionDynamicRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-condition-chain-static-spread-map" in data, data
assert b"asyncAwaitConditionDynamicRuntimeTailLabels" in data, data
assert b"patched-await-condition-chain-tail-map" in data, data
assert b"asyncAwaitConditionDynamicRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-chain-dynamic-map" in data, data
assert b"asyncAwaitConditionDynamicDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-double-dynamic-runtime-map" in data, data
assert b"asyncAwaitConditionDynamicDynamicDynamicLabels" in data, data
assert b"patched-await-condition-triple-dynamic-map" in data, data
assert b"asyncAwaitConditionRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-reverse-chain-map" in data, data
assert b"asyncAwaitConditionRuntimeDynamicStaticSpreadLabels" in data, data
assert b"patched-await-condition-reverse-chain-static-spread-map" in data, data
assert b"asyncAwaitConditionRuntimeDynamicTailLabels" in data, data
assert b"patched-await-condition-reverse-chain-tail-map" in data, data
assert b"asyncAwaitConditionRuntimeDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-reverse-chain-runtime-map" in data, data
assert b"asyncAwaitConditionRuntimeRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-double-runtime-dynamic-map" in data, data
assert b"asyncAwaitConditionRuntimeRuntimeRuntimeLabels" in data, data
assert b"patched-await-condition-triple-runtime-map" in data, data
assert b"asyncAwaitConditionDynamicTailLabels" in data, data
assert b"patched-await-condition-tail-chain-map" in data, data
assert b"asyncAwaitConditionRuntimeTailLabels" in data, data
assert b"patched-await-condition-runtime-tail-map" in data, data
assert b"asyncAwaitConditionDynamicStaticSpreadLabels" in data, data
assert b"patched-await-condition-static-spread-map" in data, data
assert b"asyncAwaitConditionRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-condition-runtime-static-spread-map" in data, data
assert b"asyncAwaitThenDynamicLabels" in data, data
assert b"patched-await-dynamic-map" in data, data
assert b"asyncAwaitThenRuntimeForLabels" in data, data
assert b"patched-await-runtime-for" in data, data
assert b"patched-async-static" in data, data
assert b"asyncDirectCallbackMixed" in data, data
assert b"patched-async-mixed" in data, data
assert b"asyncAwaitThenDirectCallbackMixed" in data, data
assert b"patched-await-callback" in data, data
assert b"asyncArithmeticValue" in data, data
assert b"asyncAwaitThenArithmeticValue" in data, data
assert b"asyncSubtractValue" in data, data
assert b"asyncAwaitThenSubtractValue" in data, data
assert b"asyncMultiplyValue" in data, data
assert b"asyncAwaitThenMultiplyValue" in data, data
assert b"asyncDivideValue" in data, data
assert b"asyncAwaitThenDivideValue" in data, data
assert b"asyncLogicalFlag" in data, data
assert b"asyncAwaitThenLogicalFlag" in data, data
assert b"asyncAlwaysThrow" in data, data
assert b"patched-async-boom" in data, data
assert b"asyncAwaitThenAlwaysThrow" in data, data
assert b"patched-await-throw:" in data, data
assert b"asyncStaticHelperValue" in data, data
assert b"asyncAwaitThenStaticHelperValue" in data, data
assert b"asyncAwaitThenStaticCombine" in data, data
assert b"combine" in data, data
assert b"asyncConcatLabel" in data, data
assert b"asyncAwaitThenConcatLabel" in data, data
assert b"patched-await-concat " in data, data
assert b"asyncNullableChoice" in data, data
assert b"patched-null" in data, data
assert b"asyncAwaitThenNullableChoice" in data, data
assert b"patched-await-null" in data, data
assert b"asyncGeneratedCatchAwaitForRecoveryFinallyYieldStarCleanup" in data, data
assert b"patched-stream-catch-await-for-recovery-finally-yield-star-body-" in data, data
assert b"asyncGeneratedCatchYieldStarRecoveryFinallyAwaitForCleanup" in data, data
assert b"patched-stream-catch-yield-star-recovery-finally-await-for-cleanup-" in data, data
assert b"asyncGeneratedStreamCollectionSwitchFinallyYieldStar" in data, data
assert b"patched-stream-collection-switch-finally-yield-star-premium" in data, data
assert b"asyncGeneratedStreamMapSwitchCatchAwaitForFinallyCleanup" in data, data
assert b"patched-stream-map-switch-catch-await-for-finally-cleanup-" in data, data
assert b"asyncGeneratedNestedCatchAwaitForFinallyYieldStarCleanup" in data, data
assert b"patched-stream-nested-catch-await-for-finally-yield-star-inner-" in data, data
assert b"asyncGeneratedYieldStarNestedCatchFinallyAwaitForCleanup" in data, data
assert b"patched-stream-yield-star-nested-catch-finally-await-for-cleanup-" in data, data
assert b"asyncGeneratedAwaitForCatchCollectionFinallyAwaitFor" in data, data
assert b"patched-stream-await-for-catch-collection-finally-extra-" in data, data
assert b"asyncGeneratedYieldStarCatchMapCollectionFinallyYieldStar" in data, data
assert b"patched-stream-yield-star-catch-map-finally-extra-" in data, data
assert b"asyncGeneratedSequentialAwaitForFinallyTwoCleanups" in data, data
assert b"patched-stream-sequential-finally-two-cleanups-cleanup-" in data, data
assert b"asyncGeneratedYieldStarCatchAwaitForSwitchRecoveryFinallyYieldStar" in data, data
assert b"patched-stream-yield-star-catch-switch-recovery-premium-" in data, data
assert b"asyncGeneratedNestedAwaitForCatchFinallyCollectionCleanup" in data, data
assert b"patched-stream-nested-await-for-collection-cleanup-extra-" in data, data
assert b"asyncGeneratedYieldStarCatchFinallyMapCleanup" in data, data
assert b"patched-stream-yield-star-catch-finally-map-extra-" in data, data
assert b"asyncGeneratedAwaitForCatchYieldStarFinallyAwaitForTail" in data, data
assert b"patched-stream-await-for-catch-yield-star-finally-tail-cleanup-" in data, data
assert b"asyncGeneratedYieldStarThenNestedAwaitForFinallyCollection" in data, data
assert b"patched-stream-yield-star-nested-await-for-finally-collection-extra-" in data, data
assert b"asyncGeneratedTripleYieldStarCatchFinallyAwaitForCleanup" in data, data
assert b"patched-stream-triple-yield-star-catch-finally-cleanup-caught-" in data, data
assert b"asyncGeneratedAwaitForSwitchCatchMapFinallyYieldStarCleanup" in data, data
assert b"patched-stream-await-for-switch-catch-map-finally-premium-" in data, data
assert b"asyncWhileAwaitConditionNestedCollectionTryCatchFinallyGuard" in data, data
assert b"patched-while-await-condition-nested-collection-premium-" in data, data
assert b"asyncForAwaitConditionSwitchMapTryFinallyAwaitGuard" in data, data
assert b"patched-for-await-condition-switch-map-premium-" in data, data
assert b"asyncWhileMultiAwaitUpdateCollectionTryCatchFinallyGuard" in data, data
assert b"patched-while-multi-await-update-collection-cleanup-" in data, data
assert b"asyncDoWhileSwitchMapNestedTryCatchFinallyGuard" in data, data
assert b"patched-do-switch-map-nested-finalizer-premium-" in data, data
assert b"asyncWhileSwitchCollectionFinallyNestedCleanupGuard" in data, data
assert b"patched-while-switch-collection-nested-cleanup-premium" in data, data
assert b"asyncWhileAwaitConditionMapTryCatchFinallyDoubleCleanupGuard" in data, data
assert b"patched-while-await-condition-map-double-cleanup-caught-" in data, data
assert b"asyncWhileAwaitConditionSwitchCollectionDoubleCleanupGuard" in data, data
assert b"patched-while-await-condition-switch-collection-double-cleanup-premium" in data, data
assert b"asyncDoWhileAwaitConditionMapTryCatchDoubleCleanupGuard" in data, data
assert b"patched-do-await-condition-map-double-cleanup-caught-" in data, data
assert b"asyncWhileNestedSwitchCollectionTryCatchFinallyGuard" in data, data
assert b"patched-while-nested-switch-collection-finalizer-premium-" in data, data
assert b"asyncDoWhileNestedSwitchMapTryFinallyDoubleCleanupGuard" in data, data
assert b"patched-do-nested-switch-map-double-cleanup-premium-" in data, data
assert b"asyncForAwaitConditionCollectionTryFinallyDoubleCleanupGuard" in data, data
assert b"patched-for-await-condition-collection-double-cleanup-body-" in data, data
assert b"asyncWhileRuntimeMapTryCatchFinallyRecoveryCleanupGuard" in data, data
assert b"patched-while-runtime-map-recovery-cleanup-caught-" in data, data
assert b"asyncWhileAwaitConditionMapTryCatchFinallyRecoveryCleanupGuard" in data, data
assert b"patched-while-await-condition-map-recovery-cleanup-caught-" in data, data
assert b"asyncDoWhileSwitchCollectionTryCatchFinallyRecoveryGuard" in data, data
assert b"patched-do-switch-collection-recovery-premium" in data, data
assert b"asyncWhileNestedListTryFinallyDoubleCleanupGuard" in data, data
assert b"patched-while-nested-list-double-cleanup-premium-" in data, data
assert b"asyncForSwitchCollectionTryFinallyDoubleCleanupGuard" in data, data
assert b"patched-for-switch-collection-double-cleanup-premium" in data, data
assert b"asyncDoWhileAwaitConditionSwitchCollectionTryFinallyDoubleCleanupGuard" in data, data
assert b"patched-do-await-condition-switch-collection-double-cleanup-premium" in data, data
assert b"asyncWhileMapSwitchTryCatchFinallyRecoveryDoubleCleanupGuard" in data, data
assert b"patched-while-map-switch-recovery-double-cleanup-premium" in data, data
assert b"asyncGeneratedAwaitForCatchYieldStarFinallyDoubleAwaitForCleanup" in data, data
assert b"patched-stream-await-for-catch-yield-star-double-cleanup-cleanup-" in data, data
assert b"asyncGeneratedYieldStarCatchAwaitForFinallyListCleanupTail" in data, data
assert b"patched-stream-yield-star-catch-await-for-list-cleanup-extra-" in data, data
assert b"asyncGeneratedNestedAwaitForInnerCatchFinallyYieldStarCleanup" in data, data
assert b"patched-stream-nested-inner-catch-yield-star-cleanup-caught-" in data, data
assert b"asyncGeneratedYieldStarCatchMapRecoveryFinallyAwaitForCleanupTail" in data, data
assert b"patched-stream-yield-star-map-recovery-await-cleanup-tail-" in data, data
assert b"asyncGeneratedSequentialYieldStarAwaitForFinallyYieldStarTail" in data, data
assert b"patched-stream-sequential-yield-star-await-for-tail-body-" in data, data
assert b"asyncGeneratedAwaitForSwitchCatchFinallyListCleanupTail" in data, data
assert b"patched-stream-await-for-switch-list-cleanup-premium-" in data, data
assert b"syncGeneratedDynamicSpreadNestedSwitchList" in data, data
assert b"patched-iterable-dynamic-spread-nested-switch-list-premium" in data, data
assert b"syncGeneratedDynamicSpreadNestedForList" in data, data
assert b"patched-iterable-dynamic-spread-nested-for-list-tier-" in data, data
assert b"syncGeneratedDynamicSpreadNestedSwitchMap" in data, data
assert b"patched-iterable-dynamic-spread-nested-switch-map-premium" in data, data
assert b"asyncGeneratedAwaitDynamicSpreadNestedSwitchList" in data, data
assert b"patched-stream-await-dynamic-spread-nested-switch-list-premium" in data, data
assert b"asyncGeneratedDynamicSpreadSwitchTryFinallyDoubleCleanupList" in data, data
assert b"patched-stream-dynamic-spread-switch-double-cleanup-list-cleanup-" in data, data
assert b"asyncGeneratedDynamicSpreadSwitchTryCatchFinallyDoubleAwaitMap" in data, data
assert b"patched-stream-dynamic-spread-switch-double-await-map-caught-" in data, data
assert b"asyncGeneratedAwaitThenDynamicSpreadRuntimeMap" in data, data
assert b"patched-stream-await-then-dynamic-spread-runtime-map-for-" in data, data
assert b"asyncGeneratedAwaitDynamicSpreadNestedSwitchMap" in data, data
assert b"patched-stream-await-dynamic-spread-nested-switch-map-premium" in data, data
assert b"asyncGeneratedDynamicSpreadNestedSwitchMapTryFinallyDoubleCleanup" in data, data
assert b"patched-stream-dynamic-spread-nested-switch-map-double-cleanup-" in data, data
assert b"asyncGeneratedDynamicSpreadNestedSwitchMapTryCatchFinallyDoubleAwait" in data, data
assert b"patched-stream-dynamic-spread-nested-switch-map-catch-caught-" in data, data
assert b"asyncMapForListSourceSwitchChain" in data, data
assert b"patched-async-map-for-list-source-switch-premium" in data, data
assert b"asyncMapForListSourceTryFinallyCleanup" in data, data
assert b"patched-async-map-for-list-source-finally-cleanup-" in data, data
assert b"asyncMapForListSourceTryCatchFinallyRecovery" in data, data
assert b"patched-async-map-for-list-source-catch-caught-" in data, data
assert b"asyncMapForListSourceWhileTryFinallyLoop" in data, data
assert b"patched-async-map-for-list-source-while-cleanup-" in data, data
assert b"asyncMapForListSourceForSwitchFinallyChain" in data, data
assert b"patched-async-map-for-list-source-for-cleanup-" in data, data
assert b"asyncMapForListSourceDoWhileCatchFinallyChain" in data, data
assert b"patched-async-map-for-list-source-do-caught-" in data, data
assert b"asyncMapForListSourceNestedBranchRecovery" in data, data
assert b"patched-async-map-for-list-source-branch-caught-" in data, data
assert b"asyncListForSourceDoubleAwaitSwitchChain" in data, data
assert b"patched-async-list-for-source-switch-premium" in data, data
assert b"asyncListForSourceWhileTryFinallyLoop" in data, data
assert b"patched-async-list-for-source-while-cleanup-" in data, data
assert b"asyncListForSourceForTryCatchFinallyRecovery" in data, data
assert b"patched-async-list-for-source-for-caught-" in data, data
assert b"asyncListForSourceDoWhileCatchFinallyChain" in data, data
assert b"patched-async-list-for-source-do-caught-" in data, data
assert b"asyncListForSourceNestedBranchRecovery" in data, data
assert b"patched-async-list-for-source-branch-caught-" in data, data
assert b"asyncNotAwaitCollectionIfListChain" in data, data
assert b"patched-async-not-await-list-live-" in data, data
assert b"asyncNotAwaitCollectionIfMapChain" in data, data
assert b"patched-async-not-await-map-live-" in data, data
assert b"asyncNotAwaitCollectionIfTryFinallyListCleanup" in data, data
assert b"patched-async-not-await-list-finally-cleanup-" in data, data
assert b"asyncNotAwaitCollectionIfTryCatchFinallyMapRecovery" in data, data
assert b"patched-async-not-await-map-caught-" in data, data
assert b"asyncNotAwaitIfTryFinallyTail" in data, data
assert b"patched-async-not-await-if-finally" in data, data
assert b"asyncNotAwaitIfElseTryCatchFinallyTail" in data, data
assert b"patched-async-not-await-ifelse" in data, data
assert b"asyncNotAwaitWhileTryFinallyLoop" in data, data
assert b"patched-async-not-await-while" in data, data
assert b"asyncNotAwaitForTryCatchLoop" in data, data
assert b"patched-async-not-await-for" in data, data
assert b"asyncNotAwaitDoWhileFinallyCondition" in data, data
assert b"patched-async-not-await-do" in data, data
assert b"asyncNotAwaitGuardedSwitchExprLabel" in data, data
assert b"patched-not-await-guarded-switch-expr-gold" in data, data
assert b"asyncNotAwaitGuardedSwitchExprAwaitScrutinee" in data, data
assert b"patched-not-await-guarded-switch-await-expr-gold" in data, data
assert b"asyncNotAwaitGuardedSwitchStatementLabel" in data, data
assert b"patched-not-await-guarded-switch-stmt-gold" in data, data
assert b"asyncNotAwaitGuardedSwitchStatementAwaitScrutinee" in data, data
assert b"patched-not-await-guarded-switch-await-stmt-gold" in data, data
assert b"asyncNotAwaitGuardedSwitchTryFinallyCleanup" in data, data
assert b"patched-not-await-guarded-switch-finally-gold" in data, data
assert b"asyncNotAwaitGuardedSwitchTryCatchFinallyRecovery" in data, data
assert b"patched-not-await-guarded-switch-caught-" in data, data
assert b"asyncWhileNotAwaitGuardedSwitchCollectionFinalizer" in data, data
assert b"patched-loop-not-await-guarded-switch-list-gold" in data, data
assert b"asyncDoWhileNotAwaitGuardedSwitchMapTryCatchFinally" in data, data
assert b"patched-loop-not-await-guarded-switch-map-caught-" in data, data
assert b"asyncForAwaitScrutineeNotAwaitGuardedSwitchFinally" in data, data
assert b"patched-for-await-scrutinee-not-await-guarded-switch-gold-" in data, data
assert b"asyncWhileAwaitScrutineeNotAwaitGuardedMapRecoveryCleanup" in data, data
assert b"patched-while-await-scrutinee-not-await-guarded-map-caught-" in data, data
assert b"asyncObjectCallTypeCollectionSwitchRecoveryCleanup" in data, data
assert b"patched-async-object-call-type-user" in data, data
assert b"patched-async-object-call-type-cleanup-" in data, data
assert b"asyncNamedObjectStaticCallMapRecoveryCleanup" in data, data
assert b"patched-async-named-object-map-name" in data, data
assert b"patched-async-named-object-map-cleanup-" in data, data
assert b"asyncWhileObjectDynamicTypeFinalizerChain" in data, data
assert b"patched-async-object-loop-while-user" in data, data
assert b"patched-async-object-loop-while-cleanup-" in data, data
assert b"asyncForNamedObjectStaticMapCatchFinallyChain" in data, data
assert b"patched-async-object-loop-for-blocked" in data, data
assert b"patched-async-object-loop-for-cleanup-" in data, data
assert b"asyncDoWhileObjectCallCollectionRecoveryCleanupChain" in data, data
assert b"patched-async-object-loop-do-caught-" in data, data
assert b"patched-async-object-loop-do-cleanup-" in data, data
assert b"asyncGeneratedObjectDynamicTypeAwaitForCleanup" in data, data
assert b"patched-stream-object-dynamic-type-user" in data, data
assert b"patched-stream-object-dynamic-type-cleanup-" in data, data
assert b"asyncGeneratedNamedObjectStaticYieldStarRecovery" in data, data
assert b"patched-stream-named-object-static-name" in data, data
assert b"patched-stream-named-object-static-caught-" in data, data
assert b"asyncGeneratedObjectCallAwaitForYieldStarFinally" in data, data
assert b"patched-stream-object-call-await-for-" in data, data
assert b"patched-stream-object-call-await-for-cleanup-" in data, data
assert b"asyncGeneratedObjectSwitchListRecoveryCleanup" in data, data
assert b"patched-stream-object-switch-list-user" in data, data
assert b"patched-stream-object-switch-list-cleanup-" in data, data
assert b"asyncGeneratedNamedObjectSwitchMapYieldStarCleanup" in data, data
assert b"patched-stream-object-switch-map-name" in data, data
assert b"patched-stream-object-switch-map-cleanup-" in data, data
assert b"asyncGeneratedObjectSwitchAwaitForYieldStarFinally" in data, data
assert b"patched-stream-object-switch-await-for-gold-" in data, data
assert b"patched-stream-object-switch-await-for-cleanup-" in data, data
assert b"syncGeneratedObjectSwitchListRecoveryCleanup" in data, data
assert b"patched-iterable-object-switch-list-user" in data, data
assert b"patched-iterable-object-switch-list-cleanup-head" in data, data
assert b"syncGeneratedNamedObjectSwitchMapYieldStarCleanup" in data, data
assert b"patched-iterable-object-switch-map-name" in data, data
assert b"patched-iterable-object-switch-map-cleanup-head" in data, data
assert b"syncGeneratedObjectSwitchForInYieldStarFinally" in data, data
assert b"patched-iterable-object-switch-for-in-gold-" in data, data
assert b"patched-iterable-object-switch-for-in-cleanup-head" in data, data
assert b"syncGeneratedWhileObjectDynamicTypeFinalizerChain" in data, data
assert b"patched-iterable-object-loop-while-user" in data, data
assert b"patched-iterable-object-loop-while-cleanup-head-" in data, data
assert b"syncGeneratedForNamedObjectStaticMapCatchFinallyChain" in data, data
assert b"patched-iterable-object-loop-for-blocked" in data, data
assert b"patched-iterable-object-loop-for-cleanup-head-" in data, data
assert b"syncGeneratedDoWhileObjectCallCollectionRecoveryCleanupChain" in data, data
assert b"patched-iterable-object-loop-do-is-" in data, data
assert b"patched-iterable-object-loop-do-caught-" in data, data
assert b"patched-iterable-object-loop-do-cleanup-head-" in data, data
assert b"asyncGeneratedWhileObjectDynamicTypeFinalizerChain" in data, data
assert b"patched-stream-object-loop-while-user" in data, data
assert b"patched-stream-object-loop-while-cleanup-" in data, data
assert b"asyncGeneratedForNamedObjectStaticMapCatchFinallyChain" in data, data
assert b"patched-stream-object-loop-for-blocked" in data, data
assert b"patched-stream-object-loop-for-cleanup-head-" in data, data
assert b"asyncGeneratedDoWhileObjectCallCollectionRecoveryCleanupChain" in data, data
assert b"patched-stream-object-loop-do-is-" in data, data
assert b"patched-stream-object-loop-do-cleanup-" in data, data
assert b"asyncGeneratedWhileAwaitForObjectSwitchCollectionCleanup" in data, data
assert b"patched-stream-nested-loop-switch-list-user" in data, data
assert b"patched-stream-nested-loop-switch-list-cleanup-" in data, data
assert b"asyncGeneratedForAwaitForNamedMapYieldStarCleanup" in data, data
assert b"patched-stream-nested-loop-switch-map-name" in data, data
assert b"patched-stream-nested-loop-switch-map-cleanup-head" in data, data
assert b"syncGeneratedWhileForInObjectSwitchCollectionCleanup" in data, data
assert b"patched-iterable-nested-loop-switch-list-user" in data, data
assert b"patched-iterable-nested-loop-switch-list-cleanup-" in data, data
assert b"syncGeneratedForForInNamedMapYieldStarCleanup" in data, data
assert b"patched-iterable-nested-loop-switch-map-name" in data, data
assert b"patched-iterable-nested-loop-switch-map-cleanup-head" in data, data
assert b"asyncListDynamicSpreadRuntimeForDeepChain" in data, data
assert b"patched-async-list-deep-spread-head" in data, data
assert b"patched-async-list-deep-spread-extra-live-" in data, data
assert b"asyncListDeepSpreadTryCatchFinallyChain" in data, data
assert b"patched-async-list-deep-spread-caught-" in data, data
assert b"asyncMapDynamicSpreadRuntimeForDeepChain" in data, data
assert b"patched-async-map-deep-spread-head" in data, data
assert b"asyncMapDeepSpreadTryCatchFinallyChain" in data, data
assert b"patched-async-map-deep-spread-cleanup-" in data, data
assert b"asyncListAwaitConditionSpreadForStaticSuperChain" in data, data
assert b"patched-async-list-super-static-spread" in data, data
assert b"asyncListLoopCollectionRecoveryCleanupSuperChain" in data, data
assert b"patched-async-list-loop-super-cleanup-" in data, data
assert b"asyncMapAwaitConditionSpreadForStaticSuperChain" in data, data
assert b"patched-async-map-super-static-spread" in data, data
assert b"asyncMapLoopCollectionRecoveryCleanupSuperChain" in data, data
assert b"patched-async-map-loop-super-cleanup-" in data, data
assert b"asyncGeneratedNestedAwaitForRecoveryDoubleCleanupSuperChain" in data, data
assert b"patched-stream-super-nested-cleanup-" in data, data
assert b"asyncGeneratedYieldStarAwaitForMapRecoveryCleanupTailSuperChain" in data, data
assert b"patched-stream-super-map-cleanup-" in data, data
assert b"asyncGeneratedWhileYieldStarAwaitForSwitchCleanupSuperChain" in data, data
assert b"patched-stream-super-while-cleanup-" in data, data
assert b"asyncGeneratedStreamGuardedContinueBreakRecoveryCleanupSuperChain" in data, data
assert b"patched-stream-guarded-super-cleanup-" in data, data
assert b"asyncGeneratedNestedStreamGuardedRecoveryCleanupSuperChain" in data, data
assert b"patched-stream-nested-guarded-super-caught-" in data, data
assert b"asyncGeneratedWhileStreamGuardedDoubleCleanupSuperChain" in data, data
assert b"patched-stream-while-guarded-super-cleanup-" in data, data
assert b"asyncGeneratedStreamPendingContinueRecoveryCleanupSuperChain" in data, data
assert b"patched-stream-pending-continue-cleanup-" in data, data
assert b"asyncGeneratedStreamPendingBreakRecoveryCleanupSuperChain" in data, data
assert b"patched-stream-pending-break-caught-" in data, data
assert b"asyncGeneratedNestedStreamPendingGuardSuperChain" in data, data
assert b"patched-stream-pending-nested-cleanup-" in data, data
assert b"asyncGeneratedYieldAwaitListValueSuperChain" in data, data
assert b"patched-stream-yield-await-list-premium-" in data, data
assert b"asyncGeneratedYieldAwaitMapSwitchValueSuperChain" in data, data
assert b"patched-stream-yield-await-map-premium-" in data, data
assert b"asyncGeneratedYieldAwaitStringValueSuperChain" in data, data
assert b"patched-stream-yield-await-string-cleanup-" in data, data
assert b"asyncGeneratedYieldAwaitListCollectionForSuperChain" in data, data
assert b"patched-stream-yield-await-list-for-cleanup-" in data, data
assert b"asyncGeneratedYieldAwaitMapCollectionForSuperChain" in data, data
assert b"patched-stream-yield-await-map-for-cleanup-" in data, data
assert b"asyncGeneratedYieldStarAwaitStreamFutureSuperChain" in data, data
assert b"patched-stream-yield-star-await-stream-cleanup-" in data, data
assert b"asyncGeneratedYieldStarAwaitStreamFutureCatchFinallySuperChain" in data, data
assert b"patched-stream-yield-star-await-stream-caught-" in data, data
assert b"asyncGeneratedAwaitForAwaitStreamFutureSuperChain" in data, data
assert b"patched-stream-await-for-await-stream-cleanup-" in data, data
assert b"asyncGeneratedAwaitForAwaitStreamFutureCatchFinallySuperChain" in data, data
assert b"patched-stream-await-for-await-stream-catch-cleanup-" in data, data
assert b"asyncGeneratedYieldStarSwitchSelectedAwaitStreamSuperChain" in data, data
assert b"patched-stream-switch-selected-yield-star-cleanup-" in data, data
assert b"asyncGeneratedAwaitForSwitchSelectedAwaitStreamSuperChain" in data, data
assert b"patched-stream-switch-selected-await-for-cleanup-" in data, data
assert b"asyncGeneratedSwitchSelectedYieldStarThenAwaitForFinallySuperChain" in data, data
assert b"patched-stream-switch-selected-finalizer-body-" in data, data
assert b"asyncGeneratedNestedSwitchSelectedAwaitForFinallySuperChain" in data, data
assert b"patched-stream-switch-selected-finalizer-cleanup-" in data, data
assert b"asyncGeneratedTripleSwitchSelectedAwaitForFinalizerSuperChain" in data, data
assert b"patched-stream-triple-switch-finalizer-body-" in data, data
assert b"asyncGeneratedTripleSwitchSelectedYieldStarRecoverySuperChain" in data, data
assert b"patched-stream-triple-switch-recovery-cleanup-" in data, data
assert b"asyncGeneratedListCollectionAwaitForFinalizerSuperChain" in data, data
assert b"patched-stream-collection-finalizer-cleanup" in data, data
assert b"asyncGeneratedMapCollectionCatchFinallySuperChain" in data, data
assert b"patched-stream-map-finalizer-cleanup" in data, data
assert b"asyncGeneratedListRuntimeForAwaitSourceCleanupSuperChain" in data, data
assert b"patched-stream-awaited-list-source-cleanup-" in data, data
assert b"asyncGeneratedMapEntriesAwaitSourceCleanupSuperChain" in data, data
assert b"patched-stream-awaited-map-source-cleanup" in data, data
assert b"asyncListAwaitedRuntimeSourcesSuperChain" in data, data
assert b"patched-async-awaited-list-source-head" in data, data
assert b"asyncMapEntriesAwaitedRuntimeSourcesSuperChain" in data, data
assert b"patched-async-awaited-map-source-head" in data, data
assert b"asyncListAwaitedRuntimeSourcesTryCatchSwitchSuperChain" in data, data
assert b"patched-async-awaited-list-try-caught-" in data, data
assert b"asyncMapAwaitedEntriesTryCatchSwitchSuperChain" in data, data
assert b"patched-async-awaited-map-try-caught" in data, data
assert b"asyncListAwaitedRuntimeSourcesFinallyCleanupSuperChain" in data, data
assert b"patched-async-awaited-list-finally-cleanup" in data, data
assert b"asyncMapAwaitedRuntimeSourcesFinallyCleanupSuperChain" in data, data
assert b"patched-async-awaited-map-finally-cleanup" in data, data
print("kernel binary compile-from-plan drill passed")
