import struct
import sys

data = open(sys.argv[1], "rb").read()
assert data[:4] == b"FCBM", data[:4]
version = struct.unpack(">I", data[4:8])[0]
function_count = struct.unpack(">H", data[8:10])[0]
assert version == 3, version
assert function_count == 523, function_count
assert b"\x50" in data, data
assert b"\x40" in data, data
assert b"\x41" in data, data
assert b"\x42" in data, data
assert b"\x43" in data, data
assert b"\x44" in data, data
assert b"\x45" in data, data
assert b"\x55" in data, data
assert b"\x54" in data, data
assert b"\x60" in data, data
assert b"\x61" in data, data
assert b"\x62" in data, data
assert b"\x63" in data, data
assert b"\x64" in data, data
assert b"\x51" in data, data
assert b"\x53" in data, data
assert b"\x03" in data, data
assert b"\x04" in data, data
assert b"\x31" in data, data
assert b"\x30" in data, data
assert b"enabled" in data, data
assert b"premium" in data, data
assert b"state" in data, data
assert b"tier" in data, data
assert b"ready" in data, data
assert b"keepGoing" in data, data
assert b"next" in data, data
assert b"segment" in data, data
assert b"j" in data, data
assert b"prefix" in data, data
assert b"syncLocalMutation" in data, data
assert b"patched-local" in data, data
assert b"asyncLocalMutation" in data, data
assert b"patched-async-local" in data, data
assert b"asyncAwaitThenLocalMutation" in data, data
assert b"patched-await-local:" in data, data
assert b"asyncUpdateConfigLabel" in data, data
assert b"async-patched" in data, data
assert b"asyncAwaitThenUpdateConfigLabel" in data, data
assert b"await-patched" in data, data
assert b"asyncDynamicNamedCall" in data, data
assert b"asyncAwaitThenDynamicCall" in data, data
assert b"patched-await-dynamic<" in data, data
assert b"patched-async" in data, data
assert b"asyncSameObject" in data, data
assert b"asyncAwaitThenSameObject" in data, data
assert b"asyncAwaitThenIsString" in data, data
assert b"asyncAwaitThenAsStringList" in data, data
assert b"dart:core::identical" in data, data
assert b"asyncDisplayName" in data, data
assert b"asyncAwaitThenReadField" in data, data
assert b"patched-await-field" in data, data
assert b"asyncMakeUser" in data, data
assert b"asyncAwaitThenMakeUser" in data, data
assert b"patched-await-user" in data, data
assert b"asyncMakeConfig" in data, data
assert b"asyncAwaitThenMakeConfig" in data, data
assert b"patched-await-config" in data, data
assert b"asyncMakeStringBox" in data, data
assert b"asyncAwaitThenMakeStringBox" in data, data
assert b"patched-await-box:" in data, data
assert b"package:fcb_kernel_compile_test/main.dart::class:Box.;types:String" in data, data
assert b"patched-async-label" in data, data
assert b"asyncWhileNestedAwaitBranchLocal" in data, data
assert b"patched-while-nested-await-branch" in data, data
assert b"asyncForNestedAwaitBranchLocal" in data, data
assert b"patched-for-nested-await-branch" in data, data
assert b"asyncForAwaitUpdateNestedBranchLocal" in data, data
assert b"patched-for-await-update-nested-branch" in data, data
assert b"asyncForTryFinallyAwaitGuard" in data, data
assert b"patched-for-try-finally-await-guard" in data, data
assert b"asyncForTryFinallyAwaitGuardAwaitUpdate" in data, data
assert b"patched-for-try-finally-await-guard-update" in data, data
assert b"asyncForTryCatchAwaitGuard" in data, data
assert b"patched-for-try-catch-await-guard" in data, data
assert b"asyncForTryCatchAwaitGuardAwaitUpdate" in data, data
assert b"patched-for-try-catch-await-guard-update" in data, data
assert b"asyncForAwaitConditionTryFinallyAwaitGuardAwaitUpdate" in data, data
assert b"patched-for-await-condition-try-finally-update" in data, data
assert b"asyncForAwaitConditionTryCatchAwaitGuardAwaitUpdate" in data, data
assert b"patched-for-await-condition-try-catch-update" in data, data
assert b"asyncWhileTryCatchAwaitGuard" in data, data
assert b"patched-while-try-catch-await-guard" in data, data
assert b"asyncWhileTryFinallyAwaitGuard" in data, data
assert b"patched-while-try-finally-await-guard" in data, data
assert b"asyncWhileAwaitConditionTryCatchAwaitGuard" in data, data
assert b"patched-while-await-condition-try-catch" in data, data
assert b"asyncWhileAwaitConditionTryFinallyAwaitGuard" in data, data
assert b"patched-while-await-condition-try-finally" in data, data
assert b"asyncDoWhileTryCatchAwaitGuard" in data, data
assert b"patched-do-while-try-catch-await-guard" in data, data
assert b"asyncDoWhileTryFinallyAwaitGuard" in data, data
assert b"patched-do-while-try-finally-await-guard" in data, data
assert b"asyncDoWhileAwaitConditionTryCatchAwaitGuard" in data, data
assert b"patched-do-while-await-condition-try-catch" in data, data
assert b"asyncDoWhileAwaitConditionTryFinallyAwaitGuard" in data, data
assert b"patched-do-while-await-condition-try-finally" in data, data
assert b"asyncForMultiUpdateBranchLocal" in data, data
assert b"patched-for-multi-update-pro" in data, data
assert b"asyncForAwaitConditionMultiUpdateBranchLocal" in data, data
assert b"patched-for-await-condition-multi-update-pro" in data, data
assert b"asyncForMultiUpdateTryFinallyAwaitGuard" in data, data
assert b"patched-for-multi-update-try-finally" in data, data
assert b"asyncForAwaitConditionMultiUpdateTryCatchAwaitGuard" in data, data
assert b"patched-for-await-condition-multi-update-error-" in data, data
assert b"asyncGeneratedYieldStarStreamCatch" in data, data
assert b"patched-stream-yield-star-stream-caught-" in data, data
assert b"asyncGeneratedYieldStarStreamCatchFinally" in data, data
assert b"patched-stream-yield-star-stream-catch-finally-cleanup" in data, data
assert b"asyncGeneratedYieldStarTwoStreamsCatchFinally" in data, data
assert b"patched-stream-yield-star-two-streams-catch-finally-cleanup" in data, data
assert b"asyncCollectionSwitchSpreadNames" in data, data
assert b"patched-collection-switch-list-premium" in data, data
assert b"patched-collection-switch-list-for-" in data, data
assert b"asyncCollectionSwitchSpreadLabels" in data, data
assert b"patched-collection-switch-map-premium" in data, data
assert b"patched-collection-switch-map-for-" in data, data
assert b"asyncCollectionSwitchTryFinallyNames" in data, data
assert b"patched-collection-switch-try-finally-list-cleanup" in data, data
assert b"asyncCollectionSwitchTryCatchLabels" in data, data
assert b"patched-collection-switch-try-catch-map-caught-" in data, data
assert b"asyncAwaitThenCollectionSwitchSpreadNames" in data, data
assert b"patched-await-then-collection-switch-list-premium" in data, data
assert b"patched-await-then-collection-switch-list-for-" in data, data
assert b"asyncAwaitThenCollectionSwitchSpreadLabels" in data, data
assert b"patched-await-then-collection-switch-map-premium" in data, data
assert b"patched-await-then-collection-switch-map-for-" in data, data
assert b"asyncAwaitThenCollectionSwitchTryFinallyNames" in data, data
assert b"patched-await-then-collection-switch-try-finally-list-cleanup" in data, data
assert b"asyncAwaitThenCollectionSwitchTryCatchLabels" in data, data
assert b"patched-await-then-collection-switch-try-catch-map-caught-" in data, data
assert b"asyncDoubleAwaitCollectionSwitchSpreadNames" in data, data
assert b"patched-double-await-collection-switch-list-premium" in data, data
assert b"patched-double-await-collection-switch-list-for-" in data, data
assert b"asyncDoubleAwaitCollectionSwitchSpreadLabels" in data, data
assert b"patched-double-await-collection-switch-map-premium" in data, data
assert b"patched-double-await-collection-switch-map-for-" in data, data
assert b"asyncDoubleAwaitCollectionSwitchTryFinallyNames" in data, data
assert b"patched-double-await-collection-switch-try-finally-list-cleanup" in data, data
assert b"asyncDoubleAwaitCollectionSwitchTryCatchLabels" in data, data
assert b"patched-double-await-collection-switch-try-catch-map-caught-" in data, data
assert b"asyncGeneratedAwaitForStreamCatch" in data, data
assert b"patched-stream-await-for-stream-caught-" in data, data
assert b"asyncGeneratedAwaitForStreamCatchFinally" in data, data
assert b"patched-stream-await-for-stream-catch-finally-cleanup" in data, data
assert b"asyncGeneratedAwaitForTwoStreamsCatchFinally" in data, data
assert b"patched-stream-await-for-two-streams-catch-finally-cleanup" in data, data
assert b"asyncGeneratedYieldStarStreamSandwichCatchFinally" in data, data
assert b"patched-stream-yield-star-stream-sandwich-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarTwoStreamsSandwichCatchFinally" in data, data
assert b"patched-stream-yield-star-two-streams-sandwich-cleanup" in data, data
assert b"asyncGeneratedYieldStarTripleStreamsCatchFinally" in data, data
assert b"patched-stream-yield-star-triple-streams-cleanup" in data, data
assert b"asyncGeneratedAwaitForNestedStreamCatchFinally" in data, data
assert b"patched-stream-await-for-nested-stream-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForNestedStreamBreakContinueCatchFinally" in data, data
assert b"patched-stream-await-for-nested-stream-break-continue-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForTripleNestedStreamCatchFinally" in data, data
assert b"patched-stream-await-for-triple-nested-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarDynamicCatchFinally" in data, data
assert b"patched-stream-yield-star-dynamic-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarFromFutureCatchFinally" in data, data
assert b"patched-stream-yield-star-future-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarPendingFutureCatchFinally" in data, data
assert b"patched-stream-yield-star-pending-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForFromIterableCatchFinally" in data, data
assert b"patched-stream-await-for-iterable-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForFutureCatchFinally" in data, data
assert b"patched-stream-await-for-future-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForPendingFutureCatchFinally" in data, data
assert b"patched-stream-await-for-pending-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarValueCatchFinally" in data, data
assert b"patched-stream-yield-star-value-catch-cleanup" in data, data
assert b"asyncGeneratedYieldStarEmptyCatchFinally" in data, data
assert b"patched-stream-yield-star-empty-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForValueCatchFinally" in data, data
assert b"patched-stream-await-for-value-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForEmptyCatchFinally" in data, data
assert b"patched-stream-await-for-empty-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForFutureBreakCatchFinally" in data, data
assert b"patched-stream-await-for-future-break-catch-cleanup" in data, data
assert b"asyncGeneratedAwaitForPendingContinueCatchFinally" in data, data
assert b"patched-stream-await-for-pending-continue-catch-cleanup" in data, data
assert b"syncGeneratedSwitchOrPatternExpr" in data, data
assert b"patched-iterable-switch-or-premium" in data, data
assert b"syncGeneratedSwitchOrPatternStatement" in data, data
assert b"patched-iterable-switch-stmt-or-premium" in data, data
assert b"asyncGeneratedSwitchOrPatternExpr" in data, data
assert b"patched-stream-switch-or-premium" in data, data
assert b"asyncGeneratedSwitchOrPatternStatement" in data, data
assert b"patched-stream-switch-stmt-or-premium" in data, data
assert b"syncGeneratedWhileSwitchOrPatternStatement" in data, data
assert b"patched-iterable-while-switch-or-premium-" in data, data
assert b"syncGeneratedForSwitchOrPatternStatement" in data, data
assert b"patched-iterable-for-switch-or-premium-" in data, data
assert b"asyncGeneratedWhileSwitchOrPatternStatement" in data, data
assert b"patched-stream-while-switch-or-premium-" in data, data
assert b"asyncGeneratedForSwitchOrPatternStatement" in data, data
assert b"patched-stream-for-switch-or-premium-" in data, data
assert b"asyncGeneratedAwaitForSwitchOrPatternStatement" in data, data
assert b"patched-stream-await-for-switch-or-premium-" in data, data
assert b"asyncGeneratedNestedAwaitForSwitchOrPatternStatement" in data, data
assert b"patched-stream-nested-await-for-switch-or-premium-" in data, data
assert b"asyncGeneratedAwaitForSwitchOrPatternCatchFinally" in data, data
assert b"patched-stream-await-for-switch-or-catch-premium-" in data, data
assert b"patched-stream-await-for-switch-or-cleanup" in data, data
assert b"asyncGeneratedAwaitForSwitchOrPatternBreakContinueFinally" in data, data
assert b"patched-stream-await-for-switch-or-break-continue-premium-" in data, data
assert b"patched-stream-await-for-switch-or-break-continue-cleanup" in data, data
assert b"asyncGeneratedNestedAwaitForSwitchOrPatternCatchFinally" in data, data
assert b"patched-stream-nested-await-for-switch-or-catch-premium-" in data, data
assert b"patched-stream-nested-await-for-switch-or-cleanup" in data, data
assert b"asyncGeneratedNestedAwaitForSwitchOrPatternBreakContinueFinally" in data, data
assert b"patched-stream-nested-await-for-switch-or-break-continue-premium-" in data, data
assert b"patched-stream-nested-await-for-switch-or-break-continue-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchDynamicRuntimeNames" in data, data
assert b"patched-await-condition-try-catch-list-caught-" in data, data
assert b"asyncAwaitThenTryFinallyDynamicRuntimeNames" in data, data
assert b"patched-await-then-try-finally-list-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyRuntimeDynamicNames" in data, data
assert b"patched-await-condition-try-catch-finally-list-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-try-catch-map-caught-" in data, data
assert b"asyncAwaitThenTryFinallyDynamicRuntimeLabels" in data, data
assert b"patched-await-then-try-finally-map-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-try-catch-finally-map-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchDynamicRuntimeStaticSpreadNames" in data, data
assert b"patched-await-condition-try-catch-list-static-tail-a" in data, data
assert b"asyncAwaitThenTryFinallyRuntimeDynamicStaticSpreadNames" in data, data
assert b"patched-await-then-try-finally-list-static-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyDynamicRuntimeTailNames" in data, data
assert b"patched-await-condition-try-catch-finally-list-tail-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchDynamicRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-condition-try-catch-map-static-tail-a" in data, data
assert b"asyncAwaitThenTryFinallyRuntimeDynamicStaticSpreadLabels" in data, data
assert b"patched-await-then-try-finally-map-static-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyDynamicRuntimeTailLabels" in data, data
assert b"patched-await-condition-try-catch-finally-map-tail-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchRuntimeDynamicRuntimeNames" in data, data
assert b"patched-await-condition-try-catch-list-rdr-caught-" in data, data
assert b"asyncAwaitThenTryFinallyDynamicRuntimeDynamicNames" in data, data
assert b"patched-await-then-try-finally-list-drd-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyRuntimeRuntimeDynamicNames" in data, data
assert b"patched-await-condition-try-catch-finally-list-rrd-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchRuntimeDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-try-catch-map-rdr-caught-" in data, data
assert b"asyncAwaitThenTryFinallyDynamicRuntimeDynamicLabels" in data, data
assert b"patched-await-then-try-finally-map-drd-cleanup" in data, data
assert b"asyncAwaitConditionTryCatchFinallyRuntimeRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-try-catch-finally-map-rrd-cleanup" in data, data
assert b"asyncCollectionTryCatchAwaitRecoveryNames" in data, data
assert b"patched-collection-try-catch-await-list-caught-" in data, data
assert b"asyncCollectionTryFinallyAwaitCleanupNames" in data, data
assert b"patched-collection-try-finally-await-list-cleanup-" in data, data
assert b"asyncCollectionTryCatchFinallyAwaitRecoveryNames" in data, data
assert b"patched-collection-try-catch-finally-await-list-cleanup-" in data, data
assert b"asyncCollectionTryCatchAwaitRecoveryLabels" in data, data
assert b"patched-collection-try-catch-await-map-caught-" in data, data
assert b"asyncCollectionTryFinallyAwaitCleanupLabels" in data, data
assert b"patched-collection-try-finally-await-map-cleanup-" in data, data
assert b"asyncCollectionTryCatchFinallyAwaitRecoveryLabels" in data, data
assert b"patched-collection-try-catch-finally-await-map-cleanup-" in data, data
assert b"syncSwitchLabel" in data, data
assert b"patched-switch-gold" in data, data
assert b"syncSwitchMultiValueLabel" in data, data
assert b"patched-switch-premium" in data, data
assert b"asyncSwitchLabel" in data, data
assert b"patched-async-switch-gold" in data, data
assert b"asyncSwitchMultiValueLabel" in data, data
assert b"patched-async-switch-premium" in data, data
assert b"asyncAwaitThenSwitchLabel" in data, data
assert b"patched-await-switch-gold" in data, data
assert b"asyncAwaitThenSwitchMultiValueLabel" in data, data
assert b"patched-await-switch-premium" in data, data
assert b"syncSwitchScore" in data, data
assert b"syncSwitchMultiValueScore" in data, data
assert b"switchListNames" in data, data
assert b"patched-switch-list-gold" in data, data
assert b"switchMapLabels" in data, data
assert b"patched-switch-map-seven" in data, data
assert b"syncSwitchStatementLabel" in data, data
assert b"patched-switch-stmt-gold" in data, data
assert b"asyncSwitchStatementLabel" in data, data
assert b"patched-async-switch-stmt-gold" in data, data
assert b"asyncAwaitThenSwitchStatementLabel" in data, data
assert b"patched-await-switch-stmt-gold" in data, data
assert b"syncSwitchStatementScore" in data, data
assert b"switchStatementListNames" in data, data
assert b"patched-switch-stmt-list-gold" in data, data
assert b"switchStatementMapLabels" in data, data
assert b"patched-switch-stmt-map-seven" in data, data
assert b"syncSwitchStatementAssignedLabel" in data, data
assert b"patched-switch-stmt-assigned-gold" in data, data
assert b"asyncSwitchStatementAssignedLabel" in data, data
assert b"patched-async-switch-stmt-assigned-gold" in data, data
assert b"asyncAwaitThenSwitchStatementAssignedLabel" in data, data
assert b"patched-await-switch-stmt-assigned-gold" in data, data
assert b"syncSwitchStatementAssignedScore" in data, data
assert b"syncSwitchStatementThrowLabel" in data, data
assert b"patched-switch-stmt-throw-blocked" in data, data
assert b"asyncSwitchStatementThrowLabel" in data, data
assert b"patched-async-switch-stmt-throw-blocked" in data, data
assert b"asyncAwaitThenSwitchStatementThrowLabel" in data, data
assert b"patched-await-switch-stmt-throw-blocked" in data, data
assert b"syncSwitchStatementSequenceLabel" in data, data
assert b"patched-switch-stmt-seq-blocked" in data, data
assert b"asyncSwitchStatementSequenceLabel" in data, data
assert b"patched-async-switch-stmt-seq-blocked" in data, data
assert b"asyncAwaitThenSwitchStatementSequenceLabel" in data, data
assert b"patched-await-switch-stmt-seq-blocked" in data, data
assert b"syncSwitchStatementSideEffectTail" in data, data
assert b"patched-switch-stmt-side-suffix-gold" in data, data
assert b"asyncSwitchStatementSideEffectTail" in data, data
assert b"patched-async-switch-stmt-side-suffix-gold" in data, data
assert b"asyncAwaitThenSwitchStatementSideEffectTail" in data, data
assert b"patched-await-switch-stmt-side-suffix-gold" in data, data
assert b"asyncSwitchStatementAwaitCaseLabel" in data, data
assert b"patched-async-switch-stmt-await-case-blocked-" in data, data
assert b"asyncAwaitThenSwitchStatementAwaitCaseLabel" in data, data
assert b"patched-await-switch-stmt-await-case-blocked-" in data, data
assert b"syncSwitchStatementMultiCaseLabel" in data, data
assert b"patched-switch-stmt-multi-premium" in data, data
assert b"asyncSwitchStatementMultiCaseAssignedLabel" in data, data
assert b"patched-async-switch-stmt-multi-premium" in data, data
assert b"asyncSwitchStatementMultiCaseAwaitCaseLabel" in data, data
assert b"patched-async-switch-stmt-multi-await-blocked-" in data, data
assert b"syncSwitchStatementOrPatternLabel" in data, data
assert b"patched-switch-stmt-or-premium" in data, data
assert b"asyncSwitchStatementOrPatternAssignedLabel" in data, data
assert b"patched-async-switch-stmt-or-premium" in data, data
assert b"asyncSwitchStatementOrPatternAwaitCaseLabel" in data, data
assert b"patched-async-switch-stmt-or-await-blocked-" in data, data
assert b"asyncAwaitThenSwitchStatementOrPatternLabel" in data, data
assert b"patched-await-switch-stmt-or-premium" in data, data
assert b"switchStatementAssignedListNames" in data, data
assert b"patched-switch-stmt-assigned-list-gold" in data, data
assert b"switchStatementAssignedMapLabels" in data, data
assert b"patched-switch-stmt-assigned-map-seven" in data, data
assert b"asyncWhileSwitchAssignedLabel" in data, data
assert b"patched-while-switch-gold" in data, data
assert b"asyncWhileAwaitConditionSwitchAssignedLabel" in data, data
assert b"patched-while-await-switch-gold" in data, data
assert b"asyncForSwitchAssignedLabel" in data, data
assert b"patched-for-switch-gold" in data, data
assert b"asyncForAwaitUpdateSwitchAssignedLabel" in data, data
assert b"patched-for-await-update-switch-gold" in data, data
assert b"asyncForSwitchAssignedListNames" in data, data
assert b"patched-for-switch-list-gold" in data, data
assert b"asyncForSwitchAssignedMapLabels" in data, data
assert b"patched-for-switch-map-seven" in data, data
assert b"asyncDoWhileSwitchAssignedLabel" in data, data
assert b"patched-do-while-switch-gold" in data, data
assert b"asyncWhileSwitchOrPatternAssignedLabel" in data, data
assert b"patched-while-switch-or-premium" in data, data
assert b"asyncForAwaitUpdateSwitchOrPatternAssignedLabel" in data, data
assert b"patched-for-await-update-switch-or-premium" in data, data
assert b"asyncWhileNestedBranchSwitchAssignedLabel" in data, data
assert b"patched-while-nested-switch-gold" in data, data
assert b"asyncForTryCatchSwitchAssignedLabel" in data, data
assert b"patched-for-try-catch-switch-gold" in data, data
assert b"asyncForAwaitUpdateTryFinallySwitchAssignedLabel" in data, data
assert b"patched-for-await-update-try-finally-switch-gold" in data, data
assert b"asyncWhileAwaitConditionTryCatchSwitchAssignedLabel" in data, data
assert b"patched-while-await-condition-try-catch-switch-gold" in data, data
assert b"asyncWhileAwaitConditionTryCatchSwitchOrPatternAssignedLabel" in data, data
assert b"patched-while-await-condition-try-catch-switch-or-premium" in data, data
assert b"asyncDoWhileTryFinallySwitchAssignedLabel" in data, data
assert b"patched-do-while-try-finally-switch-gold" in data, data
assert b"asyncDoWhileTryFinallySwitchOrPatternAssignedLabel" in data, data
assert b"patched-do-while-try-finally-switch-or-premium" in data, data
assert b"awaitedCatchTail" in data, data
assert b"patched-catch-tail" in data, data
assert b"awaitedCatchAwaitTail" in data, data
assert b"patched-catch-await-tail" in data, data
assert b"awaitedCatchFinallyCleanup" in data, data
assert b"patched-catch-finally-ok-" in data, data
assert b"patched-catch-finally-caught-" in data, data
assert b"awaitedCatchFinallyAwaitTail" in data, data
assert b"patched-catch-finally-await-tail" in data, data
assert b"awaitedFinallyStatementTail" in data, data
assert b"patched-finally-tail" in data, data
assert b"patched-finally-tail-cleanup" in data, data
assert b"awaitedFinallyAwaitCleanupTail" in data, data
assert b"patched-finally-await-tail" in data, data
assert b"-cleanup-" in data, data
assert b"syncTryFinallyTail" in data, data
assert b"patched-sync-finally" in data, data
assert b"syncTryCatchTail" in data, data
assert b"patched-sync-catch" in data, data
assert b"syncTryCatchLocalStatementTail" in data, data
assert b"patched-sync-catch-local-statement" in data, data
assert b"patched-sync-catch-local-message-" in data, data
assert b"syncTryCatchBodyLocalStatementTail" in data, data
assert b"patched-sync-catch-body-local-statement" in data, data
assert b"patched-sync-catch-body-local-message-" in data, data
assert b"patched-sync-catch-body-local-caught-" in data, data
assert b"syncTryCatchReturnValue" in data, data
assert b"patched-catch-return-" in data, data
assert b"patched-caught-return-" in data, data
assert b"syncTryCatchLocalReturnValue" in data, data
assert b"patched-catch-local-return-" in data, data
assert b"patched-catch-local-caught-" in data, data
assert b"syncTryCatchFinallyReturnValue" in data, data
assert b"patched-catch-finally-return-" in data, data
assert b"patched-catch-finally-caught-" in data, data
assert b"patched-catch-finally-cleanup-" in data, data
assert b"syncTryCatchStatementTail" in data, data
assert b"patched-sync-catch-statement-" in data, data
assert b"syncTryFinallyStatementTail" in data, data
assert b"patched-sync-finally-statement-" in data, data
assert b"syncTryFinallyLocalStatementTail" in data, data
assert b"patched-cleanup-local-" in data, data
assert b"patched-sync-finally-local-statement-" in data, data
assert b"syncTryFinallyBodyLocalStatementTail" in data, data
assert b"patched-finally-body-local-" in data, data
assert b"patched-finally-body-cleanup-" in data, data
assert b"patched-sync-finally-body-local-statement-" in data, data
assert b"syncTryFinallyStatementVoid" in data, data
assert b"patched-void-cleanup-" in data, data
assert b"syncTryCatchStatementVoid" in data, data
assert b"patched-catch-void-" in data, data
assert b"syncTryFinallyReturnValue" in data, data
assert b"patched-finally-return-" in data, data
assert b"patched-return-cleanup-" in data, data
assert b"syncIfSideEffectTail" in data, data
assert b"patched-if-side-effect-" in data, data
assert b"patched-if-tail-" in data, data
assert b"syncIfElseSideEffectTail" in data, data
assert b"patched-ifelse-side-effect-on-" in data, data
assert b"patched-ifelse-side-effect-off-" in data, data
assert b"patched-ifelse-tail-" in data, data
assert b"syncIfElseLocalSideEffectTail" in data, data
assert b"patched-ifelse-local-on-" in data, data
assert b"patched-ifelse-local-off-" in data, data
assert b"patched-ifelse-local-tail-" in data, data
assert b"asyncIfElseSideEffectTail" in data, data
assert b"patched-ifelse-side-effect" in data, data
assert b"asyncIfSideEffectTail" in data, data
assert b"patched-if-side-effect" in data, data
assert b"asyncIfTryFinallyAwaitTail" in data, data
assert b"patched-if-try-finally-await-tail" in data, data
assert b"asyncIfTryCatchAwaitTail" in data, data
assert b"patched-if-try-catch-await-tail" in data, data
assert b"asyncIfElseTryFinallyCatchAwaitTail" in data, data
assert b"patched-ifelse-try-finally-catch-await-tail" in data, data
assert b"asyncConditionalAwaitExpr" in data, data
assert b"patched-conditional-disabled" in data, data
assert b"asyncAwaitThenChooseLabel" in data, data
assert b"patched-await-live" in data, data
assert b"asyncLessThanAwaitTail" in data, data
assert b"patched-less-than-tail" in data, data
assert b"asyncLessEqualAwaitTail" in data, data
assert b"patched-less-equal-tail" in data, data
assert b"asyncGreaterEqualAwaitTail" in data, data
assert b"patched-greater-equal-tail" in data, data
assert b"asyncNotEqualAwaitTail" in data, data
assert b"patched-not-equal-tail" in data, data
assert b"asyncIsStringList" in data, data
assert b"asyncAsStringList" in data, data
assert b"asyncDynamicNames" in data, data
assert b"asyncRuntimeForNames" in data, data
assert b"asyncRuntimeForLabels" in data, data
assert b"patched-async-for" in data, data
assert b"asyncAwaitThenRuntimeForNames" in data, data
assert b"asyncDynamicLabels" in data, data
assert b"asyncNames" in data, data
assert b"asyncAwaitThenNames" in data, data
assert b"patched-await-list" in data, data
assert b"asyncAwaitThenConditionalNames" in data, data
assert b"patched-await-if-live" in data, data
assert b"asyncAwaitThenConditionalDynamicNames" in data, data
assert b"patched-await-if-dynamic-live" in data, data
assert b"asyncAwaitThenConditionalDynamicTailNames" in data, data
assert b"patched-await-if-dynamic-tail-tail" in data, data
assert b"asyncAwaitThenConditionalDynamicStaticSpreadNames" in data, data
assert b"patched-await-if-dynamic-static-spread-tail-b" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeNames" in data, data
assert b"patched-await-if-dynamic-runtime-live" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeTailNames" in data, data
assert b"patched-await-if-dynamic-runtime-tail-tail" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeStaticSpreadNames" in data, data
assert b"patched-await-if-dynamic-runtime-static-spread-tail-b" in data, data
assert b"asyncAwaitThenConditionalRuntimeNames" in data, data
assert b"patched-await-if-runtime-live" in data, data
assert b"asyncAwaitThenConditionalRuntimeTailNames" in data, data
assert b"patched-await-if-runtime-tail-tail" in data, data
assert b"asyncAwaitThenConditionalRuntimeStaticSpreadNames" in data, data
assert b"patched-await-if-runtime-static-spread-tail-b" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicNames" in data, data
assert b"patched-await-if-runtime-dynamic-live" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicTailNames" in data, data
assert b"patched-await-if-runtime-dynamic-tail-tail" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicStaticSpreadNames" in data, data
assert b"patched-await-if-runtime-dynamic-static-spread-tail-b" in data, data
assert b"asyncAwaitConditionNames" in data, data
assert b"patched-await-condition-live" in data, data
assert b"asyncAwaitConditionDynamicNames" in data, data
assert b"patched-await-condition-dynamic-live" in data, data
assert b"asyncAwaitConditionRuntimeNames" in data, data
assert b"patched-await-condition-runtime-live" in data, data
assert b"asyncAwaitConditionDynamicRuntimeNames" in data, data
assert b"patched-await-condition-chain-live" in data, data
assert b"asyncAwaitConditionDynamicRuntimeStaticSpreadNames" in data, data
assert b"patched-await-condition-chain-static-spread-tail-b" in data, data
assert b"asyncAwaitConditionDynamicRuntimeTailNames" in data, data
assert b"patched-await-condition-chain-tail-tail" in data, data
assert b"asyncAwaitConditionDynamicRuntimeDynamicNames" in data, data
assert b"patched-await-condition-chain-dynamic-live" in data, data
assert b"asyncAwaitConditionDynamicDynamicRuntimeNames" in data, data
assert b"patched-await-condition-double-dynamic-runtime-live" in data, data
assert b"asyncAwaitConditionDynamicDynamicDynamicNames" in data, data
assert b"patched-await-condition-triple-dynamic-live" in data, data
assert b"asyncAwaitConditionRuntimeDynamicNames" in data, data
assert b"patched-await-condition-reverse-chain-live" in data, data
assert b"asyncAwaitConditionRuntimeDynamicStaticSpreadNames" in data, data
assert b"patched-await-condition-reverse-chain-static-spread-tail-b" in data, data
assert b"asyncAwaitConditionRuntimeDynamicTailNames" in data, data
assert b"patched-await-condition-reverse-chain-tail-tail" in data, data
assert b"asyncAwaitConditionRuntimeDynamicRuntimeNames" in data, data
assert b"patched-await-condition-reverse-chain-runtime-live" in data, data
assert b"asyncAwaitConditionRuntimeRuntimeDynamicNames" in data, data
assert b"patched-await-condition-double-runtime-dynamic-live" in data, data
assert b"asyncAwaitConditionRuntimeRuntimeRuntimeNames" in data, data
assert b"patched-await-condition-triple-runtime-live" in data, data
assert b"asyncAwaitConditionDynamicTailNames" in data, data
assert b"patched-await-condition-tail-chain-tail" in data, data
assert b"asyncAwaitConditionRuntimeTailNames" in data, data
assert b"patched-await-condition-runtime-tail-tail" in data, data
assert b"asyncAwaitConditionDynamicStaticSpreadNames" in data, data
assert b"patched-await-condition-static-spread-tail-b" in data, data
assert b"asyncAwaitConditionRuntimeStaticSpreadNames" in data, data
assert b"patched-await-condition-runtime-static-spread-tail-b" in data, data
assert b"asyncAwaitThenDynamicNames" in data, data
assert b"patched-await-dynamic" in data, data
assert b"asyncLabels" in data, data
assert b"asyncAwaitThenLabels" in data, data
assert b"patched-await-map" in data, data
assert b"asyncAwaitThenConditionalLabels" in data, data
assert b"patched-await-if-map" in data, data
assert b"asyncAwaitThenConditionalDynamicLabels" in data, data
assert b"patched-await-if-dynamic-map" in data, data
assert b"asyncAwaitThenConditionalDynamicTailLabels" in data, data
assert b"patched-await-if-dynamic-tail-map" in data, data
assert b"asyncAwaitThenConditionalDynamicStaticSpreadLabels" in data, data
assert b"patched-await-if-dynamic-static-spread-map" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeLabels" in data, data
assert b"patched-await-if-dynamic-runtime-map" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeTailLabels" in data, data
assert b"patched-await-if-dynamic-runtime-tail-map" in data, data
assert b"asyncAwaitThenConditionalDynamicRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-if-dynamic-runtime-static-spread-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeLabels" in data, data
assert b"patched-await-if-runtime-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeTailLabels" in data, data
assert b"patched-await-if-runtime-tail-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-if-runtime-static-spread-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicLabels" in data, data
assert b"patched-await-if-runtime-dynamic-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicTailLabels" in data, data
assert b"patched-await-if-runtime-dynamic-tail-map" in data, data
assert b"asyncAwaitThenConditionalRuntimeDynamicStaticSpreadLabels" in data, data
assert b"patched-await-if-runtime-dynamic-static-spread-map" in data, data
assert b"asyncAwaitConditionLabels" in data, data
assert b"patched-await-condition-map" in data, data
assert b"asyncAwaitConditionDynamicLabels" in data, data
assert b"patched-await-condition-dynamic-map" in data, data
assert b"asyncAwaitConditionRuntimeLabels" in data, data
assert b"patched-await-condition-runtime-map" in data, data
assert b"asyncAwaitConditionDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-chain-map" in data, data
assert b"asyncAwaitConditionDynamicRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-condition-chain-static-spread-map" in data, data
assert b"asyncAwaitConditionDynamicRuntimeTailLabels" in data, data
assert b"patched-await-condition-chain-tail-map" in data, data
assert b"asyncAwaitConditionDynamicRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-chain-dynamic-map" in data, data
assert b"asyncAwaitConditionDynamicDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-double-dynamic-runtime-map" in data, data
assert b"asyncAwaitConditionDynamicDynamicDynamicLabels" in data, data
assert b"patched-await-condition-triple-dynamic-map" in data, data
assert b"asyncAwaitConditionRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-reverse-chain-map" in data, data
assert b"asyncAwaitConditionRuntimeDynamicStaticSpreadLabels" in data, data
assert b"patched-await-condition-reverse-chain-static-spread-map" in data, data
assert b"asyncAwaitConditionRuntimeDynamicTailLabels" in data, data
assert b"patched-await-condition-reverse-chain-tail-map" in data, data
assert b"asyncAwaitConditionRuntimeDynamicRuntimeLabels" in data, data
assert b"patched-await-condition-reverse-chain-runtime-map" in data, data
assert b"asyncAwaitConditionRuntimeRuntimeDynamicLabels" in data, data
assert b"patched-await-condition-double-runtime-dynamic-map" in data, data
assert b"asyncAwaitConditionRuntimeRuntimeRuntimeLabels" in data, data
assert b"patched-await-condition-triple-runtime-map" in data, data
assert b"asyncAwaitConditionDynamicTailLabels" in data, data
assert b"patched-await-condition-tail-chain-map" in data, data
assert b"asyncAwaitConditionRuntimeTailLabels" in data, data
assert b"patched-await-condition-runtime-tail-map" in data, data
assert b"asyncAwaitConditionDynamicStaticSpreadLabels" in data, data
assert b"patched-await-condition-static-spread-map" in data, data
assert b"asyncAwaitConditionRuntimeStaticSpreadLabels" in data, data
assert b"patched-await-condition-runtime-static-spread-map" in data, data
assert b"asyncAwaitThenDynamicLabels" in data, data
assert b"patched-await-dynamic-map" in data, data
assert b"asyncAwaitThenRuntimeForLabels" in data, data
assert b"patched-await-runtime-for" in data, data
assert b"patched-async-static" in data, data
assert b"asyncDirectCallbackMixed" in data, data
assert b"patched-async-mixed" in data, data
assert b"asyncAwaitThenDirectCallbackMixed" in data, data
assert b"patched-await-callback" in data, data
assert b"asyncArithmeticValue" in data, data
assert b"asyncAwaitThenArithmeticValue" in data, data
assert b"asyncSubtractValue" in data, data
assert b"asyncAwaitThenSubtractValue" in data, data
assert b"asyncMultiplyValue" in data, data
assert b"asyncAwaitThenMultiplyValue" in data, data
assert b"asyncDivideValue" in data, data
assert b"asyncAwaitThenDivideValue" in data, data
assert b"asyncLogicalFlag" in data, data
assert b"asyncAwaitThenLogicalFlag" in data, data
assert b"asyncAlwaysThrow" in data, data
assert b"patched-async-boom" in data, data
assert b"asyncAwaitThenAlwaysThrow" in data, data
assert b"patched-await-throw:" in data, data
assert b"asyncStaticHelperValue" in data, data
assert b"asyncAwaitThenStaticHelperValue" in data, data
assert b"asyncAwaitThenStaticCombine" in data, data
assert b"combine" in data, data
assert b"asyncConcatLabel" in data, data
assert b"asyncAwaitThenConcatLabel" in data, data
assert b"patched-await-concat " in data, data
assert b"asyncNullableChoice" in data, data
assert b"patched-null" in data, data
assert b"asyncAwaitThenNullableChoice" in data, data
assert b"patched-await-null" in data, data
print("kernel binary compile-from-plan drill passed")
