def assert_generator_finalizer_chains(module):
    def assert_finalizer_chain(
        name,
        constants,
        min_streams,
        *,
        has_catch=True,
        min_conditionals=0,
    ):
        function = next(
            item for item in module["functions"] if item["name"].endswith(f"::{name}")
        )
        assert function.get("async_kind") == "async_star", function
        assert function["code"].count(0x55) >= min_streams, function
        assert function["code"].count(0x62) >= min_streams + 1, function
        assert function["code"].count(0x65) >= min_streams + 1, function
        assert function["code"].count(0x66) >= min_streams + 1, function
        assert 0x64 in function["code"], function
        if has_catch:
            assert 0x61 in function["code"], function
        if min_conditionals:
            assert function["code"].count(0x31) >= min_conditionals, function
        for value in constants:
            assert any(
                constant.get("type") == "String" and constant.get("value") == value
                for constant in function["constants"]
            ), function

    assert_finalizer_chain(
        "asyncGeneratedCatchAwaitForRecoveryFinallyYieldStarCleanup",
        [
            "patched-stream-catch-await-for-recovery-finally-yield-star-body-",
            "patched-stream-catch-await-for-recovery-finally-yield-star-caught-",
        ],
        3,
    )
    assert_finalizer_chain(
        "asyncGeneratedCatchYieldStarRecoveryFinallyAwaitForCleanup",
        [
            "patched-stream-catch-yield-star-recovery-finally-await-for-caught-",
            "patched-stream-catch-yield-star-recovery-finally-await-for-cleanup-",
        ],
        3,
    )
    assert_finalizer_chain(
        "asyncGeneratedStreamCollectionSwitchFinallyYieldStar",
        [
            "patched-stream-collection-switch-finally-yield-star-head",
            "patched-stream-collection-switch-finally-yield-star-premium",
            "patched-stream-collection-switch-finally-yield-star-body-",
        ],
        2,
        has_catch=False,
        min_conditionals=2,
)
    assert_finalizer_chain(
        "asyncGeneratedStreamMapSwitchCatchAwaitForFinallyCleanup",
        [
            "patched-stream-map-switch-catch-await-for-finally-head",
            "patched-stream-map-switch-catch-await-for-finally-premium",
            "patched-stream-map-switch-catch-await-for-finally-caught-",
            "patched-stream-map-switch-catch-await-for-finally-cleanup-",
        ],
        2,
        min_conditionals=2,
)
    assert_finalizer_chain(
        "asyncGeneratedNestedCatchAwaitForFinallyYieldStarCleanup",
        [
            "patched-stream-nested-catch-await-for-finally-yield-star-first-",
            "patched-stream-nested-catch-await-for-finally-yield-star-inner-",
            "skip-nested-finalizer",
        ],
        4,
    )
    assert_finalizer_chain(
        "asyncGeneratedYieldStarNestedCatchFinallyAwaitForCleanup",
        [
            "patched-stream-yield-star-nested-catch-finally-await-for-inner-",
            "patched-stream-yield-star-nested-catch-finally-await-for-cleanup-",
            "skip-cleanup-finalizer",
        ],
        3,
        min_conditionals=1,
    )
    assert_finalizer_chain(
        "asyncGeneratedAwaitForCatchCollectionFinallyAwaitFor",
        [
            "patched-stream-await-for-catch-collection-finally-body-",
            "patched-stream-await-for-catch-collection-finally-extra-",
            "patched-stream-await-for-catch-collection-finally-caught-",
            "patched-stream-await-for-catch-collection-finally-cleanup-",
        ],
        3,
)
    assert_finalizer_chain(
        "asyncGeneratedYieldStarCatchMapCollectionFinallyYieldStar",
        [
            "patched-stream-yield-star-catch-map-finally-caught-",
            "patched-stream-yield-star-catch-map-finally-extra-",
        ],
        3,
    )
    assert_finalizer_chain(
        "asyncGeneratedSequentialAwaitForFinallyTwoCleanups",
        [
            "patched-stream-sequential-finally-two-cleanups-first-",
            "patched-stream-sequential-finally-two-cleanups-second-",
            "patched-stream-sequential-finally-two-cleanups-cleanup-",
            "skip-second-cleanup-chain",
        ],
        4,
        has_catch=False,
        min_conditionals=1,
    )
    assert_finalizer_chain(
        "asyncGeneratedYieldStarCatchAwaitForSwitchRecoveryFinallyYieldStar",
        [
            "patched-stream-yield-star-catch-switch-recovery-premium-",
            "patched-stream-yield-star-catch-switch-recovery-standard-",
        ],
        3,
        min_conditionals=2,
    )
    assert_finalizer_chain(
        "asyncGeneratedNestedAwaitForCatchFinallyCollectionCleanup",
        [
            "patched-stream-nested-await-for-collection-cleanup-body-",
            "patched-stream-nested-await-for-collection-cleanup-extra-",
            "patched-stream-nested-await-for-collection-cleanup-caught-",
            "patched-stream-nested-await-for-collection-cleanup-cleanup-",
        ],
        4,
    )
    assert_finalizer_chain(
        "asyncGeneratedYieldStarCatchFinallyMapCleanup",
        [
            "patched-stream-yield-star-catch-finally-map-caught-",
            "patched-stream-yield-star-catch-finally-map-extra-",
        ],
        3,
    )
    assert_finalizer_chain(
        "asyncGeneratedAwaitForCatchYieldStarFinallyAwaitForTail",
        [
            "patched-stream-await-for-catch-yield-star-finally-tail-body-",
            "patched-stream-await-for-catch-yield-star-finally-tail-caught-",
            "patched-stream-await-for-catch-yield-star-finally-tail-cleanup-",
            "stop-body-tail-chain",
        ],
        4,
        min_conditionals=1,
    )
    assert_finalizer_chain(
        "asyncGeneratedYieldStarThenNestedAwaitForFinallyCollection",
        [
            "patched-stream-yield-star-nested-await-for-finally-collection-body-",
            "patched-stream-yield-star-nested-await-for-finally-collection-extra-",
            "patched-stream-yield-star-nested-await-for-finally-collection-cleanup-",
            "skip-nested-tail-chain",
        ],
        4,
        has_catch=False,
        min_conditionals=1,
    )
    assert_finalizer_chain(
        "asyncGeneratedTripleYieldStarCatchFinallyAwaitForCleanup",
        [
            "patched-stream-triple-yield-star-catch-finally-cleanup-caught-",
            "patched-stream-triple-yield-star-catch-finally-cleanup-",
            "skip-triple-cleanup",
        ],
        5,
        min_conditionals=1,
    )
    assert_finalizer_chain(
        "asyncGeneratedAwaitForSwitchCatchMapFinallyYieldStarCleanup",
        [
            "patched-stream-await-for-switch-catch-map-finally-premium-",
            "patched-stream-await-for-switch-catch-map-finally-standard-",
            "patched-stream-await-for-switch-catch-map-finally-caught-",
        ],
        3,
        min_conditionals=2,
    )
    assert_finalizer_chain(
        "asyncGeneratedAwaitForCatchYieldStarFinallyDoubleAwaitForCleanup",
        [
            "patched-stream-await-for-catch-yield-star-double-cleanup-body-",
            "patched-stream-await-for-catch-yield-star-double-cleanup-caught-",
            "patched-stream-await-for-catch-yield-star-double-cleanup-cleanup-",
            "patched-stream-await-for-catch-yield-star-double-cleanup-tail-",
            "skip-double-await-for-cleanup",
        ],
        4,
        min_conditionals=1,
    )
    assert_finalizer_chain(
        "asyncGeneratedYieldStarCatchAwaitForFinallyListCleanupTail",
        [
            "patched-stream-yield-star-catch-await-for-list-cleanup-caught-",
            "patched-stream-yield-star-catch-await-for-list-cleanup-extra-",
            "patched-stream-yield-star-catch-await-for-list-cleanup-cleanup-",
            "patched-stream-yield-star-catch-await-for-list-cleanup-tail-",
        ],
        3,
    )
    assert_finalizer_chain(
        "asyncGeneratedNestedAwaitForInnerCatchFinallyYieldStarCleanup",
        [
            "patched-stream-nested-inner-catch-yield-star-cleanup-body-",
            "patched-stream-nested-inner-catch-yield-star-cleanup-caught-",
            "stop-inner-finalizer-chain",
        ],
        4,
        min_conditionals=1,
    )
    assert_finalizer_chain(
        "asyncGeneratedYieldStarCatchMapRecoveryFinallyAwaitForCleanupTail",
        [
            "patched-stream-yield-star-map-recovery-await-cleanup-caught-",
            "patched-stream-yield-star-map-recovery-await-cleanup-extra-",
            "patched-stream-yield-star-map-recovery-await-cleanup-cleanup-",
            "patched-stream-yield-star-map-recovery-await-cleanup-tail-",
        ],
        3,
    )
    assert_finalizer_chain(
        "asyncGeneratedSequentialYieldStarAwaitForFinallyYieldStarTail",
        [
            "patched-stream-sequential-yield-star-await-for-tail-body-",
            "skip-sequential-yield-star-await-for",
        ],
        4,
        has_catch=False,
        min_conditionals=1,
    )
    assert_finalizer_chain(
        "asyncGeneratedAwaitForSwitchCatchFinallyListCleanupTail",
        [
            "patched-stream-await-for-switch-list-cleanup-premium-",
            "patched-stream-await-for-switch-list-cleanup-standard-",
            "patched-stream-await-for-switch-list-cleanup-extra-",
            "patched-stream-await-for-switch-list-cleanup-caught-",
            "patched-stream-await-for-switch-list-cleanup-cleanup-",
        ],
        3,
        min_conditionals=2,
    )
