def assert_generator_collection_chains(module):
    def function_named(name):
        return next(
            item for item in module["functions"] if item["name"].endswith(f"::{name}")
        )

    def assert_collection(
        name,
        constants,
        async_kind,
        *,
        min_awaits=0,
        has_catch=False,
        has_finally=False,
    ):
        function = function_named(name)
        assert function.get("async_kind") == async_kind, function
        assert 0x64 in function["code"], function
        assert function["code"].count(0x31) >= 1, function
        assert function["code"].count(0x62) >= min_awaits, function
        if has_catch:
            assert 0x61 in function["code"], function
        if has_finally:
            assert 0x65 in function["code"], function
            assert 0x66 in function["code"], function
        for value in constants:
            assert any(
                constant.get("type") == "String" and constant.get("value") == value
                for constant in function["constants"]
            ), function

    assert_collection(
        "syncGeneratedCollectionSwitchList",
        [
            "patched-iterable-collection-switch-head",
            "patched-iterable-collection-switch-premium",
            "patched-iterable-collection-switch-for-",
        ],
        "sync_star",
    )
    assert_collection(
        "asyncGeneratedCollectionSwitchList",
        [
            "patched-stream-collection-switch-head",
            "patched-stream-collection-switch-premium",
            "patched-stream-collection-switch-for-",
        ],
        "async_star",
    )
    assert_collection(
        "asyncGeneratedAwaitCollectionTryFinallyList",
        [
            "patched-stream-await-collection-try-finally-head",
            "patched-stream-await-collection-try-finally-cleanup-",
        ],
        "async_star",
        min_awaits=2,
        has_finally=True,
    )
    assert_collection(
        "asyncGeneratedCollectionSwitchTryCatchMap",
        [
            "patched-stream-collection-switch-map-head",
            "patched-stream-collection-switch-map-premium",
            "patched-stream-collection-switch-map-caught-",
        ],
        "async_star",
        min_awaits=1,
        has_catch=True,
    )
    assert_collection(
        "syncGeneratedGuardedCollectionSwitchMap",
        [
            "patched-iterable-guarded-collection-switch-map-head",
            "patched-iterable-guarded-collection-switch-map-premium",
        ],
        "sync_star",
    )
    assert_collection(
        "syncGeneratedNestedCollectionForSwitchList",
        [
            "patched-iterable-nested-collection-switch-head",
            "patched-iterable-nested-collection-switch-premium",
            "patched-iterable-nested-collection-switch-for-",
        ],
        "sync_star",
    )
    assert_collection(
        "asyncGeneratedAwaitThenCollectionSwitchMap",
        [
            "patched-stream-await-then-collection-switch-map-head",
            "patched-stream-await-then-collection-switch-map-premium",
        ],
        "async_star",
        min_awaits=2,
    )
    assert_collection(
        "asyncGeneratedDoubleAwaitGuardedCollectionList",
        [
            "patched-stream-double-await-guarded-collection-head",
            "patched-stream-double-await-guarded-collection-premium",
        ],
        "async_star",
        min_awaits=2,
    )
    assert_collection(
        "asyncGeneratedCollectionSwitchTryCatchFinallyList",
        [
            "patched-stream-collection-switch-list-head",
            "patched-stream-collection-switch-list-premium",
            "patched-stream-collection-switch-list-caught-",
            "patched-stream-collection-switch-list-cleanup-",
        ],
        "async_star",
        min_awaits=2,
        has_catch=True,
        has_finally=True,
    )
    assert_collection(
        "asyncGeneratedCollectionSwitchMapTryCatchFinallyAwait",
        [
            "patched-stream-collection-switch-map-finally-head",
            "patched-stream-collection-switch-map-finally-premium",
            "patched-stream-collection-switch-map-finally-caught-",
            "patched-stream-collection-switch-map-finally-cleanup-",
        ],
        "async_star",
        min_awaits=3,
        has_catch=True,
        has_finally=True,
    )
    assert_collection(
        "syncGeneratedNestedGuardedCollectionForList",
        [
            "patched-iterable-nested-guarded-collection-list-head",
            "patched-iterable-nested-guarded-collection-list-premium",
        ],
        "sync_star",
    )
    assert_collection(
        "asyncGeneratedAwaitThenNestedCollectionForSwitchList",
        [
            "patched-stream-await-then-nested-collection-list-head",
            "patched-stream-await-then-nested-collection-list-premium",
        ],
        "async_star",
        min_awaits=2,
    )
    assert_collection(
        "asyncGeneratedCollectionDynamicSpreadTryCatchFinallyList",
        [
            "patched-stream-collection-dynamic-spread-list-head",
            "patched-stream-collection-dynamic-spread-list-caught-",
            "patched-stream-collection-dynamic-spread-list-cleanup-",
        ],
        "async_star",
        min_awaits=3,
        has_catch=True,
        has_finally=True,
    )
    assert_collection(
        "asyncGeneratedCollectionDynamicSpreadTryCatchFinallyMap",
        [
            "patched-stream-collection-dynamic-spread-map-head",
            "patched-stream-collection-dynamic-spread-map-caught-",
            "patched-stream-collection-dynamic-spread-map-cleanup-",
        ],
        "async_star",
        min_awaits=3,
        has_catch=True,
        has_finally=True,
    )
    assert_collection(
        "syncGeneratedDynamicSpreadSwitchList",
        [
            "patched-iterable-dynamic-spread-switch-list-head",
            "patched-iterable-dynamic-spread-switch-list-premium",
        ],
        "sync_star",
    )
    assert_collection(
        "asyncGeneratedDynamicSpreadSwitchList",
        [
            "patched-stream-dynamic-spread-switch-list-head",
            "patched-stream-dynamic-spread-switch-list-premium",
        ],
        "async_star",
        min_awaits=1,
    )
    assert_collection(
        "syncGeneratedDynamicSpreadSwitchMap",
        [
            "patched-iterable-dynamic-spread-switch-map-head",
            "patched-iterable-dynamic-spread-switch-map-premium",
        ],
        "sync_star",
    )
    assert_collection(
        "asyncGeneratedDynamicSpreadSwitchMap",
        [
            "patched-stream-dynamic-spread-switch-map-head",
            "patched-stream-dynamic-spread-switch-map-premium",
        ],
        "async_star",
        min_awaits=1,
    )
    assert_collection(
        "asyncGeneratedDynamicSpreadSwitchTryFinallyList",
        [
            "patched-stream-dynamic-spread-switch-try-finally-list-head",
            "patched-stream-dynamic-spread-switch-try-finally-list-premium",
            "patched-stream-dynamic-spread-switch-try-finally-list-cleanup-",
        ],
        "async_star",
        min_awaits=2,
        has_finally=True,
    )
    assert_collection(
        "asyncGeneratedDynamicSpreadSwitchTryCatchFinallyMap",
        [
            "patched-stream-dynamic-spread-switch-try-catch-finally-map-head",
            "patched-stream-dynamic-spread-switch-try-catch-finally-map-premium",
            "patched-stream-dynamic-spread-switch-try-catch-finally-map-caught-",
            "patched-stream-dynamic-spread-switch-try-catch-finally-map-cleanup-",
        ],
        "async_star",
        min_awaits=4,
        has_catch=True,
        has_finally=True,
    )
    assert_collection(
        "syncGeneratedDynamicSpreadNestedSwitchList",
        [
            "patched-iterable-dynamic-spread-nested-switch-list-head",
            "patched-iterable-dynamic-spread-nested-switch-list-premium",
        ],
        "sync_star",
    )
    assert_collection(
        "syncGeneratedDynamicSpreadNestedForList",
        [
            "patched-iterable-dynamic-spread-nested-for-list-head",
            "patched-iterable-dynamic-spread-nested-for-list-tier-",
        ],
        "sync_star",
    )
    assert_collection(
        "syncGeneratedDynamicSpreadNestedSwitchMap",
        [
            "patched-iterable-dynamic-spread-nested-switch-map-head",
            "patched-iterable-dynamic-spread-nested-switch-map-premium",
        ],
        "sync_star",
    )
    assert_collection(
        "asyncGeneratedAwaitDynamicSpreadNestedSwitchList",
        [
            "patched-stream-await-dynamic-spread-nested-switch-list-head",
            "patched-stream-await-dynamic-spread-nested-switch-list-premium",
        ],
        "async_star",
        min_awaits=2,
    )
    assert_collection(
        "asyncGeneratedDynamicSpreadSwitchTryFinallyDoubleCleanupList",
        [
            "patched-stream-dynamic-spread-switch-double-cleanup-list-head",
            "patched-stream-dynamic-spread-switch-double-cleanup-list-premium",
            "patched-stream-dynamic-spread-switch-double-cleanup-list-cleanup-",
        ],
        "async_star",
        min_awaits=3,
        has_finally=True,
    )
    assert_collection(
        "asyncGeneratedDynamicSpreadSwitchTryCatchFinallyDoubleAwaitMap",
        [
            "patched-stream-dynamic-spread-switch-double-await-map-head",
            "patched-stream-dynamic-spread-switch-double-await-map-premium",
            "patched-stream-dynamic-spread-switch-double-await-map-caught-",
            "patched-stream-dynamic-spread-switch-double-await-map-cleanup-",
        ],
        "async_star",
        min_awaits=5,
        has_catch=True,
        has_finally=True,
    )
    assert_collection(
        "asyncGeneratedAwaitThenDynamicSpreadRuntimeMap",
        [
            "patched-stream-await-then-dynamic-spread-runtime-map-head",
            "patched-stream-await-then-dynamic-spread-runtime-map-for-",
        ],
        "async_star",
        min_awaits=2,
    )
    assert_collection(
        "asyncGeneratedAwaitDynamicSpreadNestedSwitchMap",
        [
            "patched-stream-await-dynamic-spread-nested-switch-map-head",
            "patched-stream-await-dynamic-spread-nested-switch-map-premium",
        ],
        "async_star",
        min_awaits=2,
    )
    assert_collection(
        "asyncGeneratedDynamicSpreadNestedSwitchMapTryFinallyDoubleCleanup",
        [
            "patched-stream-dynamic-spread-nested-switch-map-double-cleanup-head",
            "patched-stream-dynamic-spread-nested-switch-map-double-cleanup-premium",
            "patched-stream-dynamic-spread-nested-switch-map-double-cleanup-",
        ],
        "async_star",
        min_awaits=3,
        has_finally=True,
    )
    assert_collection(
        "asyncGeneratedDynamicSpreadNestedSwitchMapTryCatchFinallyDoubleAwait",
        [
            "patched-stream-dynamic-spread-nested-switch-map-catch-head",
            "patched-stream-dynamic-spread-nested-switch-map-catch-premium",
            "patched-stream-dynamic-spread-nested-switch-map-catch-caught-",
            "patched-stream-dynamic-spread-nested-switch-map-catch-cleanup-",
        ],
        "async_star",
        min_awaits=4,
        has_catch=True,
        has_finally=True,
    )
