def assert_async_loop_finalizer_guards(module):
    def function_named(name):
        return next(
            item for item in module["functions"] if item["name"].endswith(f"::{name}")
        )

    def assert_guard(name, constants, min_awaits, *, has_catch=False):
        function = function_named(name)
        assert function.get("async_kind") == "async_future", function
        assert function["code"].count(0x62) >= min_awaits, function
        assert 0x63 in function["code"], function
        assert 0x65 in function["code"], function
        assert 0x66 in function["code"], function
        assert 0x31 in function["code"], function
        if has_catch:
            assert 0x61 in function["code"], function
        for value in constants:
            assert any(
                constant.get("type") == "String" and constant.get("value") == value
                for constant in function["constants"]
            ), function

    assert_guard(
        "asyncWhileTryFinallyAwaitGuardContinueBreak",
        ["patched-while-finalizer-guard", "-finally-"],
        3,
    )
    assert_guard(
        "asyncWhileAwaitConditionTryFinallyAwaitGuardContinueBreak",
        ["patched-while-await-condition-finalizer-guard", "-finally-"],
        4,
    )
    assert_guard(
        "asyncWhileNestedTryFinallyAwaitGuardContinueBreak",
        ["patched-while-nested-finalizer-guard", "-premium-", "-finally-"],
        4,
    )
    assert_guard(
        "asyncWhileTryCatchFinallyAwaitGuardContinueBreak",
        [
            "patched-while-catch-finalizer-guard",
            "patched-while-catch-finalizer-guard-error-",
            "-finally-",
        ],
        4,
        has_catch=True,
    )
    assert_guard(
        "asyncDoWhileTryFinallyAwaitGuardContinueBreak",
        ["patched-do-finalizer-guard", "-finally-"],
        3,
    )
    assert_guard(
        "asyncDoWhileAwaitConditionTryFinallyAwaitGuardContinueBreak",
        ["patched-do-await-condition-finalizer-guard", "-finally-"],
        4,
    )
    assert_guard(
        "asyncDoWhileNestedTryFinallyAwaitGuardContinueBreak",
        ["patched-do-nested-finalizer-guard", "-premium-", "-finally-"],
        4,
    )
    assert_guard(
        "asyncDoWhileTryCatchFinallyAwaitGuardContinueBreak",
        [
            "patched-do-catch-finalizer-guard",
            "patched-do-catch-finalizer-guard-error-",
            "-finally-",
        ],
        4,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileSwitchTryFinallyAwaitGuardContinueBreak",
        ["patched-while-switch-finalizer-guard", "patched-while-switch-finalizer-gold", "-finally-"],
        3,
    )
    assert_guard(
        "asyncDoWhileSwitchTryFinallyAwaitGuardContinueBreak",
        ["patched-do-switch-finalizer-guard", "patched-do-switch-finalizer-gold", "-finally-"],
        3,
    )
    assert_guard(
        "asyncWhileSwitchOrPatternTryFinallyAwaitGuardContinueBreak",
        ["patched-while-switch-or-finalizer-guard", "patched-while-switch-or-finalizer-premium", "-finally-"],
        3,
    )
    assert_guard(
        "asyncDoWhileSwitchOrPatternTryFinallyAwaitGuardContinueBreak",
        ["patched-do-switch-or-finalizer-guard", "patched-do-switch-or-finalizer-premium", "-finally-"],
        3,
    )
    assert_guard(
        "asyncWhileCollectionTryFinallyAwaitGuardContinueBreak",
        ["patched-while-collection-finalizer-head", "patched-while-collection-finalizer-cleanup-"],
        3,
    )
    assert_guard(
        "asyncDoWhileCollectionTryFinallyAwaitGuardContinueBreak",
        ["patched-do-collection-finalizer-head", "patched-do-collection-finalizer-cleanup-"],
        3,
    )
    assert_guard(
        "asyncWhileMapCollectionTryFinallyAwaitGuardContinueBreak",
        ["patched-while-map-finalizer-head", "patched-while-map-finalizer-cleanup-"],
        3,
    )
    assert_guard(
        "asyncDoWhileMapCollectionTryFinallyAwaitGuardContinueBreak",
        ["patched-do-map-finalizer-head", "patched-do-map-finalizer-cleanup-"],
        3,
    )
    assert_guard(
        "asyncWhileCollectionSwitchForTryFinallyAwaitGuardContinueBreak",
        [
            "patched-while-collection-switch-finalizer-head",
            "patched-while-collection-switch-finalizer-premium",
            "patched-while-collection-switch-finalizer-cleanup-",
        ],
        3,
    )
    assert_guard(
        "asyncDoWhileCollectionSwitchForTryFinallyAwaitGuardContinueBreak",
        [
            "patched-do-collection-switch-finalizer-head",
            "patched-do-collection-switch-finalizer-premium",
            "patched-do-collection-switch-finalizer-cleanup-",
        ],
        3,
    )
    assert_guard(
        "asyncWhileMapSwitchForTryCatchFinallyAwaitGuardContinueBreak",
        [
            "patched-while-map-switch-finalizer-head",
            "patched-while-map-switch-finalizer-premium",
            "patched-while-map-switch-finalizer-cleanup-",
        ],
        4,
        has_catch=True,
    )
    assert_guard(
        "asyncDoWhileMapSwitchForTryCatchFinallyAwaitGuardContinueBreak",
        [
            "patched-do-map-switch-finalizer-head",
            "patched-do-map-switch-finalizer-premium",
            "patched-do-map-switch-finalizer-cleanup-",
        ],
        4,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileAwaitConditionCollectionSwitchTryFinallyAwaitGuardContinueBreak",
        [
            "patched-while-await-condition-collection-switch-finalizer-head",
            "patched-while-await-condition-collection-switch-finalizer-premium",
            "patched-while-await-condition-collection-switch-finalizer-cleanup-",
        ],
        4,
    )
    assert_guard(
        "asyncDoWhileAwaitConditionMapSwitchForTryCatchFinallyAwaitGuardContinueBreak",
        [
            "patched-do-await-condition-map-switch-finalizer-head",
            "patched-do-await-condition-map-switch-finalizer-premium",
            "patched-do-await-condition-map-switch-finalizer-cleanup-",
        ],
        5,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileNestedCollectionTryFinallyAwaitGuard",
        [
            "patched-while-nested-collection-finalizer-head",
            "patched-while-nested-collection-finalizer-premium-",
            "patched-while-nested-collection-finalizer-cleanup-",
        ],
        4,
    )
    assert_guard(
        "asyncDoWhileNestedMapTryCatchFinallyAwaitGuard",
        [
            "patched-do-nested-map-finalizer-head",
            "patched-do-nested-map-finalizer-premium-",
            "patched-do-nested-map-finalizer-cleanup-",
        ],
        5,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileAwaitConditionNestedCollectionTryCatchFinallyGuard",
        [
            "patched-while-await-condition-nested-collection-finalizer-head",
            "patched-while-await-condition-nested-collection-premium-",
            "patched-while-await-condition-nested-collection-cleanup-",
        ],
        6,
        has_catch=True,
    )
    assert_guard(
        "asyncForAwaitConditionSwitchMapTryFinallyAwaitGuard",
        [
            "patched-for-await-condition-switch-map-finalizer-head",
            "patched-for-await-condition-switch-map-premium-",
            "patched-for-await-condition-switch-map-cleanup-",
        ],
        4,
    )
    assert_guard(
        "asyncWhileMultiAwaitUpdateCollectionTryCatchFinallyGuard",
        [
            "patched-while-multi-await-update-collection-finalizer-head",
            "patched-while-multi-await-update-collection-body-",
            "patched-while-multi-await-update-collection-cleanup-",
        ],
        6,
        has_catch=True,
    )
    assert_guard(
        "asyncDoWhileSwitchMapNestedTryCatchFinallyGuard",
        [
            "patched-do-switch-map-nested-finalizer-head",
            "patched-do-switch-map-nested-finalizer-premium-",
            "patched-do-switch-map-nested-finalizer-cleanup-",
        ],
        5,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileSwitchCollectionFinallyNestedCleanupGuard",
        [
            "patched-while-switch-collection-nested-cleanup-head",
            "patched-while-switch-collection-nested-cleanup-premium",
            "patched-while-switch-collection-nested-cleanup-",
        ],
        4,
    )
    assert_guard(
        "asyncWhileAwaitConditionMapTryCatchFinallyDoubleCleanupGuard",
        [
            "patched-while-await-condition-map-double-cleanup-head",
            "patched-while-await-condition-map-double-cleanup-caught-",
            "patched-while-await-condition-map-double-cleanup-",
        ],
        7,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileAwaitConditionSwitchCollectionDoubleCleanupGuard",
        [
            "patched-while-await-condition-switch-collection-double-cleanup-head",
            "patched-while-await-condition-switch-collection-double-cleanup-premium",
            "patched-while-await-condition-switch-collection-double-cleanup-",
        ],
        5,
    )
    assert_guard(
        "asyncDoWhileAwaitConditionMapTryCatchDoubleCleanupGuard",
        [
            "patched-do-await-condition-map-double-cleanup-head",
            "patched-do-await-condition-map-double-cleanup-caught-",
            "patched-do-await-condition-map-double-cleanup-",
        ],
        7,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileNestedSwitchCollectionTryCatchFinallyGuard",
        [
            "patched-while-nested-switch-collection-finalizer-head",
            "patched-while-nested-switch-collection-finalizer-premium-",
            "patched-while-nested-switch-collection-finalizer-cleanup-",
        ],
        5,
        has_catch=True,
    )
    assert_guard(
        "asyncDoWhileNestedSwitchMapTryFinallyDoubleCleanupGuard",
        [
            "patched-do-nested-switch-map-double-cleanup-head",
            "patched-do-nested-switch-map-double-cleanup-premium-",
            "patched-do-nested-switch-map-double-cleanup-",
        ],
        5,
    )
    assert_guard(
        "asyncForAwaitConditionCollectionTryFinallyDoubleCleanupGuard",
        [
            "patched-for-await-condition-collection-double-cleanup-head",
            "patched-for-await-condition-collection-double-cleanup-body-",
            "patched-for-await-condition-collection-double-cleanup-",
        ],
        5,
    )
    assert_guard(
        "asyncWhileRuntimeMapTryCatchFinallyRecoveryCleanupGuard",
        [
            "patched-while-runtime-map-recovery-cleanup-head",
            "patched-while-runtime-map-recovery-cleanup-caught-",
            "patched-while-runtime-map-recovery-cleanup-",
        ],
        5,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileAwaitConditionMapTryCatchFinallyRecoveryCleanupGuard",
        [
            "patched-while-await-condition-map-recovery-cleanup-head",
            "patched-while-await-condition-map-recovery-cleanup-caught-",
            "patched-while-await-condition-map-recovery-cleanup-",
        ],
        6,
        has_catch=True,
    )
    assert_guard(
        "asyncDoWhileSwitchCollectionTryCatchFinallyRecoveryGuard",
        [
            "patched-do-switch-collection-recovery-head",
            "patched-do-switch-collection-recovery-premium",
            "patched-do-switch-collection-recovery-cleanup-",
        ],
        5,
        has_catch=True,
    )
    assert_guard(
        "asyncWhileNestedListTryFinallyDoubleCleanupGuard",
        [
            "patched-while-nested-list-double-cleanup-head",
            "patched-while-nested-list-double-cleanup-premium-",
            "patched-while-nested-list-double-cleanup-",
        ],
        5,
    )
    assert_guard(
        "asyncForSwitchCollectionTryFinallyDoubleCleanupGuard",
        [
            "patched-for-switch-collection-double-cleanup-head",
            "patched-for-switch-collection-double-cleanup-premium",
            "patched-for-switch-collection-double-cleanup-",
        ],
        4,
    )
    assert_guard(
        "asyncDoWhileAwaitConditionSwitchCollectionTryFinallyDoubleCleanupGuard",
        [
            "patched-do-await-condition-switch-collection-double-cleanup-head",
            "patched-do-await-condition-switch-collection-double-cleanup-premium",
            "patched-do-await-condition-switch-collection-double-cleanup-",
        ],
        5,
    )
    assert_guard(
        "asyncWhileMapSwitchTryCatchFinallyRecoveryDoubleCleanupGuard",
        [
            "patched-while-map-switch-recovery-double-cleanup-head",
            "patched-while-map-switch-recovery-double-cleanup-premium",
            "patched-while-map-switch-recovery-double-cleanup-",
        ],
        6,
        has_catch=True,
    )
