def assert_generator_stream_chains(module):
    def assert_stream_chain(
        name,
        constants,
        min_streams,
        *,
        has_catch=True,
        min_awaits_extra=2,
        min_conditionals=0,
    ):
        function = next(
            item for item in module["functions"] if item["name"].endswith(f"::{name}")
        )
        assert function.get("async_kind") == "async_star", function
        assert function["code"].count(0x55) >= min_streams, function
        assert function["code"].count(0x62) >= min_streams + min_awaits_extra, function
        assert function["code"].count(0x65) >= min_streams + 1, function
        assert function["code"].count(0x66) >= min_streams + 1, function
        assert 0x64 in function["code"], function
        if has_catch:
            assert 0x61 in function["code"], function
        if min_conditionals:
            assert function["code"].count(0x31) >= min_conditionals, function
        for value in constants:
            assert any(
                constant.get("type") == "String" and constant.get("value") == value
                for constant in function["constants"]
            ), function

    assert_stream_chain(
        "asyncGeneratedYieldStarNestedCatchFinallyAwaitRecovery",
        [
            "patched-stream-yield-star-nested-catch-finally-inner-",
            "patched-stream-yield-star-nested-catch-finally-outer-",
            "patched-stream-yield-star-nested-catch-finally-cleanup-",
        ],
        2,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarNestedFinallyAwaitCleanup",
        [
            "patched-stream-yield-star-nested-finally-inner-cleanup-",
            "patched-stream-yield-star-nested-finally-outer-cleanup-",
        ],
        2,
        has_catch=False,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForNestedCatchFinallyAwaitRecovery",
        [
            "patched-stream-await-for-nested-catch-finally-await-body-",
            "patched-stream-await-for-nested-catch-finally-await-caught-",
            "patched-stream-await-for-nested-catch-finally-await-cleanup-",
        ],
        2,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForTripleNestedCatchFinallyAwaitRecovery",
        [
            "patched-stream-await-for-triple-nested-catch-finally-await-body-",
            "patched-stream-await-for-triple-nested-catch-finally-await-caught-",
            "patched-stream-await-for-triple-nested-catch-finally-await-cleanup-",
            "skip",
            "stop-middle",
        ],
        3,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarTripleNestedCatchFinallyAwaitRecovery",
        [
            "patched-stream-yield-star-triple-nested-catch-finally-inner-",
            "patched-stream-yield-star-triple-nested-catch-finally-outer-",
            "patched-stream-yield-star-triple-nested-catch-finally-cleanup-",
        ],
        3,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarTripleNestedFinallyAwaitCleanup",
        [
            "patched-stream-yield-star-triple-nested-finally-inner-cleanup-",
            "patched-stream-yield-star-triple-nested-finally-outer-cleanup-",
        ],
        3,
        has_catch=False,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForNestedBreakContinueCatchFinallyAwaitRecovery",
        [
            "patched-stream-await-for-nested-break-continue-catch-finally-await-body-",
            "patched-stream-await-for-nested-break-continue-catch-finally-await-caught-",
            "patched-stream-await-for-nested-break-continue-catch-finally-await-cleanup-",
            "skip",
            "stop",
        ],
        2,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForTripleNestedFinallyAwaitCleanup",
        [
            "patched-stream-await-for-triple-nested-finally-await-body-",
            "patched-stream-await-for-triple-nested-finally-await-cleanup-",
            "skip",
            "stop-middle",
        ],
        3,
        has_catch=False,
        min_conditionals=2,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForSequentialCatchFinallyAwaitRecovery",
        [
            "patched-stream-await-for-sequential-catch-finally-first-",
            "patched-stream-await-for-sequential-catch-finally-second-",
            "patched-stream-await-for-sequential-catch-finally-caught-",
            "patched-stream-await-for-sequential-catch-finally-cleanup-",
        ],
        2,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForSequentialBreakContinueFinallyAwaitCleanup",
        [
            "patched-stream-await-for-sequential-break-continue-first-",
            "patched-stream-await-for-sequential-break-continue-second-",
            "patched-stream-await-for-sequential-break-continue-cleanup-",
            "skip-first",
            "stop-second",
        ],
        2,
        has_catch=False,
        min_conditionals=2,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForNestedInnerCatchOuterFinallyAwaitRecovery",
        [
            "patched-stream-await-for-nested-inner-catch-outer-finally-body-",
            "patched-stream-await-for-nested-inner-catch-outer-finally-inner-caught-",
            "patched-stream-await-for-nested-inner-catch-outer-finally-cleanup-",
            "stop-inner",
        ],
        2,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarThenAwaitForCatchFinallyAwaitRecovery",
        [
            "patched-stream-yield-star-then-await-for-catch-finally-body-",
            "patched-stream-yield-star-then-await-for-catch-finally-caught-",
            "patched-stream-yield-star-then-await-for-catch-finally-cleanup-",
            "skip-second",
        ],
        2,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForThenYieldStarFinallyAwaitCleanup",
        [
            "patched-stream-await-for-then-yield-star-finally-body-",
            "patched-stream-await-for-then-yield-star-finally-cleanup-",
            "skip-first",
        ],
        2,
        has_catch=False,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarAwaitForNestedCatchFinallyAwaitRecovery",
        [
            "patched-stream-yield-star-await-for-nested-catch-finally-body-",
            "patched-stream-yield-star-await-for-nested-catch-finally-caught-",
            "patched-stream-yield-star-await-for-nested-catch-finally-cleanup-",
            "skip-middle",
            "stop-inner",
        ],
        3,
        min_conditionals=2,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForSequentialNestedCatchFinallyAwaitRecovery",
        [
            "patched-stream-await-for-sequential-nested-catch-finally-first-",
            "patched-stream-await-for-sequential-nested-catch-finally-inner-",
            "patched-stream-await-for-sequential-nested-catch-finally-caught-",
            "patched-stream-await-for-sequential-nested-catch-finally-cleanup-",
            "skip-first-deep",
            "stop-middle-deep",
        ],
        3,
        min_conditionals=2,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForNestedThenYieldStarCatchFinallyAwaitRecovery",
        [
            "patched-stream-await-for-nested-then-yield-star-body-",
            "patched-stream-await-for-nested-then-yield-star-caught-",
            "patched-stream-await-for-nested-then-yield-star-cleanup-",
            "stop-nested-tail",
        ],
        3,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarThenAwaitForThenYieldStarCatchFinallyAwaitRecovery",
        [
            "patched-stream-yield-star-await-for-yield-star-middle-",
            "patched-stream-yield-star-await-for-yield-star-caught-",
            "patched-stream-yield-star-await-for-yield-star-cleanup-",
            "skip-middle-deep",
        ],
        3,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarNestedAwaitForThenYieldStarCatchFinallyAwaitRecovery",
        [
            "patched-stream-yield-star-nested-await-for-yield-star-body-",
            "patched-stream-yield-star-nested-await-for-yield-star-caught-",
            "patched-stream-yield-star-nested-await-for-yield-star-cleanup-",
            "skip-outer-deep",
            "stop-inner-deep",
        ],
        4,
        min_conditionals=2,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForFinallyAwaitForCleanup",
        [
            "patched-stream-await-for-finally-await-for-body-",
            "patched-stream-await-for-finally-await-for-cleanup-",
            "skip-body-finally",
        ],
        2,
        has_catch=False,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarFinallyYieldStarCleanup",
        [
            "patched-stream-yield-star-finally-yield-star-head",
            "patched-stream-yield-star-finally-yield-star-cleanup-head",
        ],
        2,
        has_catch=False,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForCatchFinallyAwaitForCleanup",
        [
            "patched-stream-await-for-catch-finally-await-for-body-",
            "patched-stream-await-for-catch-finally-await-for-caught-",
            "patched-stream-await-for-catch-finally-await-for-cleanup-",
            "stop-body-finally",
        ],
        2,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarAwaitForFinallyYieldStarCleanup",
        [
            "patched-stream-yield-star-await-for-finally-yield-star-middle-",
            "skip-middle-finally",
        ],
        3,
        has_catch=False,
        min_conditionals=1,
    )
    assert_stream_chain(
        "asyncGeneratedAwaitForYieldStarFinallyAwaitForCleanup",
        [
            "patched-stream-await-for-yield-star-finally-body-",
            "patched-stream-await-for-yield-star-finally-caught-",
            "patched-stream-await-for-yield-star-finally-cleanup-",
            "skip-await-for-yield-star-finally",
            "stop-await-for-yield-star-finally-cleanup",
        ],
        3,
        min_conditionals=2,
    )
    assert_stream_chain(
        "asyncGeneratedYieldStarFinallyAwaitForYieldStarCleanup",
        [
            "patched-stream-yield-star-finally-await-for-yield-star-head",
            "patched-stream-yield-star-finally-await-for-yield-star-cleanup-",
            "patched-stream-yield-star-finally-await-for-yield-star-middle-",
            "skip-yield-star-finally-await-for-yield-star-cleanup",
        ],
        3,
        has_catch=False,
        min_conditionals=1,
    )
