#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKDIR="${FCB_WORKDIR:-$ROOT_DIR/target/fcb/full-ios-drill}"
ARCHIVE_STAMP="${FCB_ARCHIVE_STAMP:-$(date +%Y%m%d_%H%M%S)}"
ARCHIVE_DIR="${FCB_ARCHIVE_DIR:-$ROOT_DIR/target/fcb/evidence/ios_drill_$ARCHIVE_STAMP}"
BUILD_SCRIPT="${FCB_IOS_BUILD_SCRIPT:-$ROOT_DIR/scripts/build_ios_engine.sh}"
SIM_SCRIPT="${FCB_IOS_SIM_SCRIPT:-$ROOT_DIR/scripts/test_ios_sim.sh}"
APP_DIR="${FCB_APP_DIR:-$ROOT_DIR/examples/counter_app}"
XCODE_WORKSPACE="${FCB_XCODE_WORKSPACE:-$APP_DIR/ios/Runner.xcworkspace}"
XCODE_SCHEME="${FCB_XCODE_SCHEME:-Runner}"
BUNDLE_ID="${FCB_BUNDLE_ID:-com.jinhuatoast.fcbCounterApp}"
TEAM_ID="${FCB_TEAM_ID:-}"
APP_STORE_CONNECT_TEAM_ID="${FCB_APP_STORE_CONNECT_TEAM_ID:-}"
SKIP_SIM_PREFLIGHT="${FCB_SKIP_IOS_SIM_PREFLIGHT:-0}"
SKIP_ARCHIVE="${FCB_SKIP_ARCHIVE:-0}"
H4_DEVICE_EVIDENCE="${FCB_H4_DEVICE_EVIDENCE:-}"
H4_SERVER_EVENTS_EVIDENCE="${FCB_H4_SERVER_EVENTS_EVIDENCE:-}"
H4_DEVICE_EVIDENCE_SUMMARY=""
H4_SERVER_EVENTS_EVIDENCE_SUMMARY=""

case "$WORKDIR" in
  /*) ;;
  *) WORKDIR="$ROOT_DIR/$WORKDIR" ;;
esac

usage() {
  cat <<USAGE
Usage:
  $0

Runs the Phase H4 iOS production drill entrypoint.

By default this script runs the simulator smoke path via scripts/test_ios_sim.sh,
then writes command logs for the physical iPhone install/archive path and
TestFlight upload path. The physical iPhone and App Store Connect steps still
require human-operated signing credentials and review evidence.

Environment:
  FCB_WORKDIR                 Drill output root. Default: target/fcb/full-ios-drill
  FCB_ARCHIVE_DIR             Evidence archive root. Default: target/fcb/evidence/ios_drill_<timestamp>
  FCB_ARCHIVE_STAMP           Timestamp suffix used by the default archive dir.
  FCB_SKIP_ARCHIVE            Skip copying final evidence into the archive dir. Default: 0
  FCB_SKIP_IOS_SIM_PREFLIGHT  Skip scripts/test_ios_sim.sh. Default: 0
  FCB_IOS_BUILD_SCRIPT        iOS engine build script. Default: scripts/build_ios_engine.sh
  FCB_IOS_SIM_SCRIPT          iOS simulator smoke script. Default: scripts/test_ios_sim.sh
  FCB_APP_DIR                 Flutter app directory. Default: examples/counter_app
  FCB_XCODE_WORKSPACE         Xcode workspace. Default: examples/counter_app/ios/Runner.xcworkspace
  FCB_XCODE_SCHEME            Xcode scheme. Default: Runner
  FCB_BUNDLE_ID               Bundle id. Default: com.jinhuatoast.fcbCounterApp
  FCB_TEAM_ID                 Apple signing team id, written into generated command logs.
  FCB_APP_STORE_CONNECT_TEAM_ID
                              App Store Connect provider/team id for upload logs.
  FCB_H4_DEVICE_EVIDENCE      File proving iPhone baseline/patched/restart passed.
  FCB_H4_SERVER_EVENTS_EVIDENCE
                              File proving server events for the iPhone drill.
USAGE
}

die() {
  echo "error: $*" >&2
  exit 1
}

run() {
  echo "+ $*" >&2
  "$@"
}

require_file() {
  [ -f "$1" ] || die "missing file: $1"
}

require_file_contains() {
  local file="$1"
  local pattern="$2"
  grep -Fq "$pattern" "$file" || die "evidence file $file must contain: $pattern"
}

validate_completion_evidence() {
  if [ -n "$H4_DEVICE_EVIDENCE" ] || [ -n "$H4_SERVER_EVENTS_EVIDENCE" ]; then
    [ -n "$H4_DEVICE_EVIDENCE" ] || die "FCB_H4_DEVICE_EVIDENCE is required when writing the H4 completion marker"
    [ -n "$H4_SERVER_EVENTS_EVIDENCE" ] || die "FCB_H4_SERVER_EVENTS_EVIDENCE is required when writing the H4 completion marker"
    require_file "$H4_DEVICE_EVIDENCE"
    require_file "$H4_SERVER_EVENTS_EVIDENCE"
    require_file_contains "$H4_DEVICE_EVIDENCE" "iPhone baseline patched restart passed"
    require_file_contains "$H4_SERVER_EVENTS_EVIDENCE" "launch_success"
  fi
}

stage_completion_evidence() {
  if [ -z "$H4_DEVICE_EVIDENCE" ] && [ -z "$H4_SERVER_EVENTS_EVIDENCE" ]; then
    return 0
  fi
  mkdir -p "$WORKDIR/evidence"
  local device_basename
  local events_basename
  device_basename="$(basename "$H4_DEVICE_EVIDENCE")"
  events_basename="$(basename "$H4_SERVER_EVENTS_EVIDENCE")"
  cp "$H4_DEVICE_EVIDENCE" "$WORKDIR/evidence/h4-device-$device_basename"
  cp "$H4_SERVER_EVENTS_EVIDENCE" "$WORKDIR/evidence/h4-server-events-$events_basename"
  H4_DEVICE_EVIDENCE_SUMMARY="evidence/h4-device-$device_basename"
  H4_SERVER_EVENTS_EVIDENCE_SUMMARY="evidence/h4-server-events-$events_basename"
}

write_device_command_log() {
  local out="$WORKDIR/iphone-device-commands.sh"
  cat >"$out" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/full_ios_drill.sh.
# Run on a macOS host with Xcode, a connected iPhone, and valid signing.

ROOT_DIR="\${ROOT_DIR:-$ROOT_DIR}"
APP_DIR="\${FCB_APP_DIR:-$APP_DIR}"
WORKSPACE="\${FCB_XCODE_WORKSPACE:-$XCODE_WORKSPACE}"
SCHEME="\${FCB_XCODE_SCHEME:-$XCODE_SCHEME}"
BUNDLE_ID="\${FCB_BUNDLE_ID:-$BUNDLE_ID}"
TEAM_ID="\${FCB_TEAM_ID:-$TEAM_ID}"
DERIVED_DATA="\${FCB_DERIVED_DATA:-$WORKDIR/DerivedData}"
DEVICE_ID="\${FCB_IOS_DEVICE_ID:-}"

test -n "\$TEAM_ID"
test -n "\$DEVICE_ID"

cd "\$ROOT_DIR"
FCB_IOS_CPU=arm64 FCB_RUNTIME_MODE=release "$BUILD_SCRIPT"

xcodebuild \\
  -workspace "\$WORKSPACE" \\
  -scheme "\$SCHEME" \\
  -configuration Release \\
  -destination "id=\$DEVICE_ID" \\
  -derivedDataPath "\$DERIVED_DATA" \\
  DEVELOPMENT_TEAM="\$TEAM_ID" \\
  PRODUCT_BUNDLE_IDENTIFIER="\$BUNDLE_ID" \\
  build

APP_PATH="\$(find "\$DERIVED_DATA/Build/Products" -name "*.app" -type d | head -1)"
test -n "\$APP_PATH"

xcrun devicectl device install app --device "\$DEVICE_ID" "\$APP_PATH"
xcrun devicectl device process launch --device "\$DEVICE_ID" "\$BUNDLE_ID"

echo "Record baseline, patched launch, rollback result, device logs, and server events."
EOF
  chmod +x "$out"
}

write_testflight_command_log() {
  local out="$WORKDIR/testflight-upload-commands.sh"
  cat >"$out" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/full_ios_drill.sh.
# Run only after the iPhone device drill passes.

WORKSPACE="\${FCB_XCODE_WORKSPACE:-$XCODE_WORKSPACE}"
SCHEME="\${FCB_XCODE_SCHEME:-$XCODE_SCHEME}"
BUNDLE_ID="\${FCB_BUNDLE_ID:-$BUNDLE_ID}"
TEAM_ID="\${FCB_TEAM_ID:-$TEAM_ID}"
ASC_TEAM_ID="\${FCB_APP_STORE_CONNECT_TEAM_ID:-$APP_STORE_CONNECT_TEAM_ID}"
ARCHIVE_PATH="\${FCB_ARCHIVE_PATH:-$WORKDIR/Runner.xcarchive}"
EXPORT_PATH="\${FCB_EXPORT_PATH:-$WORKDIR/export}"
EXPORT_OPTIONS="\${FCB_EXPORT_OPTIONS_PLIST:-$WORKDIR/exportOptions.plist}"

test -n "\$TEAM_ID"

xcodebuild archive \\
  -workspace "\$WORKSPACE" \\
  -scheme "\$SCHEME" \\
  -configuration Release \\
  -archivePath "\$ARCHIVE_PATH" \\
  DEVELOPMENT_TEAM="\$TEAM_ID" \\
  PRODUCT_BUNDLE_IDENTIFIER="\$BUNDLE_ID"

cat >"\$EXPORT_OPTIONS" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>app-store-connect</string>
  <key>teamID</key>
  <string>\$TEAM_ID</string>
  <key>uploadBitcode</key>
  <false/>
  <key>compileBitcode</key>
  <false/>
</dict>
</plist>
PLIST

xcodebuild -exportArchive \\
  -archivePath "\$ARCHIVE_PATH" \\
  -exportPath "\$EXPORT_PATH" \\
  -exportOptionsPlist "\$EXPORT_OPTIONS"

IPA_PATH="\$(find "\$EXPORT_PATH" -name "*.ipa" -type f | head -1)"
test -n "\$IPA_PATH"

if [ -n "\$ASC_TEAM_ID" ]; then
  xcrun altool --upload-app --type ios --file "\$IPA_PATH" --asc-provider "\$ASC_TEAM_ID"
else
  xcrun altool --upload-app --type ios --file "\$IPA_PATH"
fi

echo "Save App Store Connect processing status, TestFlight review result, and reviewer notes."
EOF
  chmod +x "$out"
}

write_summary() {
  local out="$WORKDIR/summary.txt"
  {
    echo "FCB iOS H4 full drill"
    echo "workdir: $WORKDIR"
    if [ "$SKIP_ARCHIVE" = "1" ]; then
      echo "archive_dir: skipped"
    else
      echo "archive_dir: $ARCHIVE_DIR"
    fi
    echo "sim_preflight: $([ "$SKIP_SIM_PREFLIGHT" = "1" ] && echo skipped || echo attempted)"
    echo "sim_script: $SIM_SCRIPT"
    echo "build_script: $BUILD_SCRIPT"
    echo "device_commands: $WORKDIR/iphone-device-commands.sh"
    echo "testflight_commands: $WORKDIR/testflight-upload-commands.sh"
    echo "known_issues: docs/known_issues.md"
    echo "compliance_notes: docs/apple_compliance.md"
    echo
    if [ -n "$H4_DEVICE_EVIDENCE" ] && [ -n "$H4_SERVER_EVENTS_EVIDENCE" ]; then
      echo "H4 iPhone device drill passed"
      echo "device_evidence: $H4_DEVICE_EVIDENCE_SUMMARY"
      echo "server_events_evidence: $H4_SERVER_EVENTS_EVIDENCE_SUMMARY"
    else
      echo "Manual Phase H4 evidence still required:"
      echo "- iPhone device baseline/patched/restart logs."
      echo "- crash rollback logs once Phase E exposes a crash-producing VM patch."
      echo "- TestFlight build processing and review result."
    fi
  } >"$out"
  echo "summary: $out"
}

archive_evidence() {
  if [ "$SKIP_ARCHIVE" = "1" ]; then
    echo "archive: skipped"
    return 0
  fi
  if [ -e "$ARCHIVE_DIR" ]; then
    die "archive dir already exists: $ARCHIVE_DIR"
  fi
  mkdir -p "$(dirname "$ARCHIVE_DIR")"
  cp -R "$WORKDIR" "$ARCHIVE_DIR"
  {
    echo
    echo "Archived Phase H4 evidence:"
    echo "- source_workdir: $WORKDIR"
    echo "- archive_dir: $ARCHIVE_DIR"
    echo "- known_issues: docs/known_issues.md"
  } >>"$ARCHIVE_DIR/summary.txt"
  echo "archive: $ARCHIVE_DIR"
}

main() {
  if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
  fi

  require_file "$BUILD_SCRIPT"
  require_file "$SIM_SCRIPT"
  validate_completion_evidence
  mkdir -p "$WORKDIR"
  stage_completion_evidence

  if [ "$SKIP_SIM_PREFLIGHT" != "1" ]; then
    FCB_WORKDIR="$WORKDIR/ios-sim-preflight" run "$SIM_SCRIPT"
  fi

  write_device_command_log
  write_testflight_command_log
  write_summary
  archive_evidence
  echo "FCB iOS H4 drill entrypoint completed."
}

main "$@"
