name: fcb_counter_app
description: FCB counter example.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fcb_code_push:
    path: ../../packages/fcb_code_push
  fcb_annotations:
    path: ../../packages/fcb_annotations
  fcb_interpreter:
    path: ../../packages/fcb_interpreter

flutter:
  uses-material-design: true
