name: Flutter Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Clean workspace
        run: sudo rm -rf "$GITHUB_WORKSPACE/.tmp" || true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Run fcb_code_push tests
        run: make test-flutter-package
